### ISSUE TITLE
[Android XOS Chameleon] 1 methods fail to translate

### ISSUE THREAD

**Issue by caochen23** [pxb1988/dex2jar#131]
Landroid/icu/text/BidiWriter;.writeReverse(Ljava/lang/String;I)Ljava/lang/String;
java.lang.RuntimeException: fail exe a28 = a5
	at com.googlecode.dex2jar.ir.ts.an.BaseAnalyze.exec(BaseAnalyze.java:92)
	at com.googlecode.dex2jar.ir.ts.an.BaseAnalyze.exec(BaseAnalyze.java:1)
	at com.googlecode.dex2jar.ir.ts.Cfg.dfs(Cfg.java:255)
	at com.googlecode.dex2jar.ir.ts.an.BaseAnalyze.analyze0(BaseAnalyze.java:75)
	at com.googlecode.dex2jar.ir.ts.an.BaseAnalyze.analyze(BaseAnalyze.java:69)
	at com.googlecode.dex2jar.ir.ts.Ir2JRegAssignTransformer.transform(Ir2JRegAssignTransformer.java:182)
	at com.googlecode.d2j.dex.Dex2jar$2.optimize(Dex2jar.java:163)
	at com.googlecode.d2j.dex.Dex2Asm.convertCode(Dex2Asm.java:433)
	at com.googlecode.d2j.dex.ExDex2Asm.convertCode(ExDex2Asm.java:42)
	at com.googlecode.d2j.dex.Dex2jar$2.convertCode(Dex2jar.java:129)
	at com.googlecode.d2j.dex.Dex2Asm.convertMethod(Dex2Asm.java:528)
	at com.googlecode.d2j.dex.Dex2Asm.convertClass(Dex2Asm.java:425)
	at com.googlecode.d2j.dex.Dex2Asm.convertDex(Dex2Asm.java:441)
	at com.googlecode.d2j.dex.Dex2jar.doTranslate(Dex2jar.java:171)
	at com.googlecode.d2j.dex.Dex2jar.to(Dex2jar.java:271)
	at com.googlecode.dex2jar.tools.Dex2jarCmd.doCommandLine(Dex2jarCmd.java:109)
	at com.googlecode.dex2jar.tools.BaseCmd.doMain(BaseCmd.java:290)
	at com.googlecode.dex2jar.tools.Dex2jarCmd.main(Dex2jarCmd.java:33)
Caused by: java.lang.NullPointerException
	at com.googlecode.dex2jar.ir.ts.an.SimpleLiveAnalyze.onUseLocal(SimpleLiveAnalyze.java:89)
	at com.googlecode.dex2jar.ir.ts.an.SimpleLiveAnalyze.onUseLocal(SimpleLiveAnalyze.java:1)
	at com.googlecode.dex2jar.ir.ts.an.BaseAnalyze.onUse(BaseAnalyze.java:166)
	at com.googlecode.dex2jar.ir.ts.an.BaseAnalyze.onUse(BaseAnalyze.java:1)
	at com.googlecode.dex2jar.ir.ts.Cfg.travel(Cfg.java:331)
	at com.googlecode.dex2jar.ir.ts.Cfg.travel(Cfg.java:387)
	at com.googlecode.dex2jar.ir.ts.an.BaseAnalyze.exec(BaseAnalyze.java:90)
	... 17 more

**Comment by caochen23** [comment]
.method static writeReverse(Ljava/lang/String;I)Ljava/lang/String;
  .registers 8
    new-instance v1, Ljava/lang/StringBuffer;
    invoke-virtual { p0 }, Ljava/lang/String;->length()I
    move-result v5
    invoke-direct { v1, v5 }, Ljava/lang/StringBuffer;-><init>(I)V
    and-int/lit8 v5, p1, 11
    packed-switch v5, :L13
    invoke-virtual { p0 }, Ljava/lang/String;->length()I
    move-result v4
  :L0
    move v2, v4
    add-int/lit8 v5, v4, -1
    invoke-static { p0, v5 }, Landroid/icu/text/UTF16;->charAt(Ljava/lang/String;I)I
    move-result v0
    invoke-static { v0 }, Landroid/icu/text/UTF16;->getCharCount(I)I
    move-result v5
    sub-int/2addr v4, v5
    and-int/lit8 v5, p1, 1
    if-eqz v5, :L9
  :L1
    if-lez v4, :L9
    invoke-static { v0 }, Landroid/icu/lang/UCharacter;->getType(I)I
    move-result v5
    invoke-static { v5 }, Landroid/icu/text/BidiWriter;->IsCombining(I)Z
    move-result v5
    if-eqz v5, :L9
    add-int/lit8 v5, v4, -1
    invoke-static { p0, v5 }, Landroid/icu/text/UTF16;->charAt(Ljava/lang/String;I)I
    move-result v0
    invoke-static { v0 }, Landroid/icu/text/UTF16;->getCharCount(I)I
    move-result v5
    sub-int/2addr v4, v5
    goto :L1
  :L2
    invoke-virtual { p0 }, Ljava/lang/String;->length()I
    move-result v4
  :L3
    move v2, v4
    add-int/lit8 v5, v4, -1
    invoke-static { p0, v5 }, Landroid/icu/text/UTF16;->charAt(Ljava/lang/String;I)I
    move-result v5
    invoke-static { v5 }, Landroid/icu/text/UTF16;->getCharCount(I)I
    move-result v5
    sub-int/2addr v4, v5
    invoke-virtual { p0, v4, v2 }, Ljava/lang/String;->substring(II)Ljava/lang/String;
    move-result-object v5
    invoke-virtual { v1, v5 }, Ljava/lang/StringBuffer;->append(Ljava/lang/String;)Ljava/lang/StringBuffer;
    if-gtz v4, :L3
  :L4
    invoke-virtual { v1 }, Ljava/lang/StringBuffer;->toString()Ljava/lang/String;
    move-result-object v5
    return-object v5
  :L5
    invoke-virtual { p0 }, Ljava/lang/String;->length()I
    move-result v4
  :L6
    move v2, v4
  :L7
    add-int/lit8 v5, v4, -1
    invoke-static { p0, v5 }, Landroid/icu/text/UTF16;->charAt(Ljava/lang/String;I)I
    move-result v0
    invoke-static { v0 }, Landroid/icu/text/UTF16;->getCharCount(I)I
    move-result v5
    sub-int/2addr v4, v5
    if-lez v4, :L8
    invoke-static { v0 }, Landroid/icu/lang/UCharacter;->getType(I)I
    move-result v5
    invoke-static { v5 }, Landroid/icu/text/BidiWriter;->IsCombining(I)Z
    move-result v5
    if-nez v5, :L7
  :L8
    invoke-virtual { p0, v4, v2 }, Ljava/lang/String;->substring(II)Ljava/lang/String;
    move-result-object v5
    invoke-virtual { v1, v5 }, Ljava/lang/StringBuffer;->append(Ljava/lang/String;)Ljava/lang/StringBuffer;
    if-lez v4, :L4
    goto :L6
  :L9
    and-int/lit8 v5, p1, 8
    if-eqz v5, :L11
    invoke-static { v0 }, Landroid/icu/text/Bidi;->IsBidiControlChar(I)Z
    move-result v5
    if-eqz v5, :L11
  :L10
    if-lez v4, :L4
    goto :L0
  :L11
    move v3, v4
    and-int/lit8 v5, p1, 2
    if-eqz v5, :L12
    invoke-static { v0 }, Landroid/icu/lang/UCharacter;->getMirror(I)I
    move-result v0
    invoke-static { v1, v0 }, Landroid/icu/text/UTF16;->append(Ljava/lang/StringBuffer;I)Ljava/lang/StringBuffer;
    invoke-static { v0 }, Landroid/icu/text/UTF16;->getCharCount(I)I
    move-result v5
    add-int/2addr v3, v5
  :L12
    invoke-virtual { p0, v3, v2 }, Ljava/lang/String;->substring(II)Ljava/lang/String;
    move-result-object v5
    invoke-virtual { v1, v5 }, Ljava/lang/StringBuffer;->append(Ljava/lang/String;)Ljava/lang/StringBuffer;
    goto :L10
  :L13
  .packed-switch 0
    :L2
    :L5
  .end packed-switch
.end method
