### ISSUE TITLE
Regression: head cannot dex2jar some dex version 035 bytecode

### ISSUE THREAD

**Issue by Lanchon** [pxb1988/dex2jar#136]
head (1d515072d5a49a8f82a761a8081e36b1923af541) cannot dex2jar some dex version 035 bytecode that older dex2jar versions were able to handle.

examples:
'core' jars from all AOSP version from 1.5 to 6.0.

one such jar can be found [here](https://github.com/Lanchon/haystack/blob/master/bulk-patch-builder/filesets/10-2.3.7-cm-7.2.0-crespo/core.jar).
corresponding dex2jar output:
```
$ d2j-dex2jar core.jar 
dex2jar core.jar -> ./core-dex2jar.jar
java.lang.NullPointerException
	at com.googlecode.d2j.dex.LambadaNameSafeClassAdapter$1.mapType(LambadaNameSafeClassAdapter.java:16)
	at org.objectweb.asm.commons.RemappingClassAdapter.visit(RemappingClassAdapter.java:66)
	at org.objectweb.asm.ClassVisitor.visit(ClassVisitor.java:113)
	at com.googlecode.d2j.dex.Dex2Asm.convertClass(Dex2Asm.java:394)
	at com.googlecode.d2j.dex.Dex2Asm.convertDex(Dex2Asm.java:450)
	at com.googlecode.d2j.dex.Dex2jar.doTranslate(Dex2jar.java:126)
	at com.googlecode.d2j.dex.Dex2jar.to(Dex2jar.java:275)
	at com.googlecode.dex2jar.tools.Dex2jarCmd.doCommandLine(Dex2jarCmd.java:107)
	at com.googlecode.dex2jar.tools.BaseCmd.doMain(BaseCmd.java:290)
	at com.googlecode.dex2jar.tools.Dex2jarCmd.main(Dex2jarCmd.java:33)
```

**Comment by Lanchon** [comment]
i can confirm that dd9d7221e448ceb834d923cb9bb3bc528cb3acd9 from 2017-01-18 does not have the issue.
so the bug was introduced in these commits: https://github.com/pxb1988/dex2jar/compare/dd9d7221e448ceb834d923cb9bb3bc528cb3acd9...1d515072d5a49a8f82a761a8081e36b1923af541

**Comment by Lanchon** [comment]
the bug was introduced in bac5d542a63543e6242162d581906a9ffb2e45fc.

**Comment by Lanchon** [comment]
Fixed here: https://github.com/Lanchon/dex2jar/commit/909c1ef5e427ebcf41bece63bab98c1cf152c4ea

**Comment by Lanchon** [comment]
Later fixed in official: https://github.com/pxb1988/dex2jar/commit/90f8d1eb809d59327ccfe03488f31da505086dfb
