### ISSUE TITLE
Error when transfer com.douban.frodo

### ISSUE THREAD

**Issue by lancer26** [pxb1988/dex2jar#137]
summary.txt

> There are 1 methods fail to translate.
2017-09-14 02:22:12 UTC
version: [dex-reader-2.0, dex-reader-api-2.0, dex-ir-2.0, d2j-smali-2.0, d2j-base-cmd-2.0, dex-tools-2.0, dex-translator-2.0]
cmdline: [com.douban.frodo.apk]
env:
java.runtime.name: Java(TM) SE Runtime Environment
java.vm.version: 25.144-b01
java.vm.vendor: Oracle Corporation
java.vendor.url: http://java.oracle.com/
java.vm.name: Java HotSpot(TM) 64-Bit Server VM
java.vm.specification.name: Java Virtual Machine Specification
java.runtime.version: 1.8.0_144-b01
java.awt.graphicsenv: sun.awt.CGraphicsEnvironment
java.endorsed.dirs: /Library/Java/JavaVirtualMachines/jdk1.8.0_144.jdk/Contents/Home/jre/lib/endorsed
java.io.tmpdir: /var/folders/sy/r2jg6z8j67q6d60pttnldj100000gn/T/
java.vm.specification.vendor: Oracle Corporation
java.library.path: /Users/lance/Library/Java/Extensions:/Library/Java/Extensions:/Network/Library/Java/Extensions:/System/Library/Java/Extensions:/usr/lib/java:.
java.specification.name: Java Platform API Specification
java.class.version: 52.0
java.awt.printerjob: sun.lwawt.macosx.CPrinterJob
java.specification.version: 1.8
java.class.path: .:/usr/local/bin/../Cellar/dex2jar/2.0/bin/../libexec/lib/antlr-runtime-3.5.jar:/usr/local/bin/../Cellar/dex2jar/2.0/bin/../libexec/lib/asm-debug-all-4.1.jar:/usr/local/bin/../Cellar/dex2jar/2.0/bin/../libexec/lib/d2j-base-cmd-2.0.jar:/usr/local/bin/../Cellar/dex2jar/2.0/bin/../libexec/lib/d2j-jasmin-2.0.jar:/usr/local/bin/../Cellar/dex2jar/2.0/bin/../libexec/lib/d2j-smali-2.0.jar:/usr/local/bin/../Cellar/dex2jar/2.0/bin/../libexec/lib/dex-ir-2.0.jar:/usr/local/bin/../Cellar/dex2jar/2.0/bin/../libexec/lib/dex-reader-2.0.jar:/usr/local/bin/../Cellar/dex2jar/2.0/bin/../libexec/lib/dex-reader-api-2.0.jar:/usr/local/bin/../Cellar/dex2jar/2.0/bin/../libexec/lib/dex-tools-2.0.jar:/usr/local/bin/../Cellar/dex2jar/2.0/bin/../libexec/lib/dex-translator-2.0.jar:/usr/local/bin/../Cellar/dex2jar/2.0/bin/../libexec/lib/dex-writer-2.0.jar:/usr/local/bin/../Cellar/dex2jar/2.0/bin/../libexec/lib/dx-1.7.jar
java.vm.specification.version: 1.8
java.home: /Library/Java/JavaVirtualMachines/jdk1.8.0_144.jdk/Contents/Home/jre
java.specification.vendor: Oracle Corporation
java.vm.info: mixed mode
java.version: 1.8.0_144
java.ext.dirs: /Users/lance/Library/Java/Extensions:/Library/Java/JavaVirtualMachines/jdk1.8.0_144.jdk/Contents/Home/jre/lib/ext:/Library/Java/Extensions:/Network/Library/Java/Extensions:/System/Library/Java/Extensions:/usr/lib/java
java.vendor: Oracle Corporation
java.vendor.url.bug: http://bugreport.sun.com/bugreport/

m-0.txt
> Lcom/douban/insight/ReportGenerator;.a(Ljava/util/List;)Lcom/douban/insight/model/FullReport;
java.lang.RuntimeException: fail exe a7 = a3
	at com.googlecode.dex2jar.ir.ts.an.BaseAnalyze.exec(BaseAnalyze.java:92)
	at com.googlecode.dex2jar.ir.ts.an.BaseAnalyze.exec(BaseAnalyze.java:1)
	at com.googlecode.dex2jar.ir.ts.Cfg.dfs(Cfg.java:255)
	at com.googlecode.dex2jar.ir.ts.an.BaseAnalyze.analyze0(BaseAnalyze.java:75)
	at com.googlecode.dex2jar.ir.ts.an.BaseAnalyze.analyze(BaseAnalyze.java:69)
	at com.googlecode.dex2jar.ir.ts.UnSSATransformer.transform(UnSSATransformer.java:274)
	at com.googlecode.d2j.dex.Dex2jar$2.optimize(Dex2jar.java:163)
	at com.googlecode.d2j.dex.Dex2Asm.convertCode(Dex2Asm.java:414)
	at com.googlecode.d2j.dex.ExDex2Asm.convertCode(ExDex2Asm.java:42)
	at com.googlecode.d2j.dex.Dex2jar$2.convertCode(Dex2jar.java:128)
	at com.googlecode.d2j.dex.Dex2Asm.convertMethod(Dex2Asm.java:509)
	at com.googlecode.d2j.dex.Dex2Asm.convertClass(Dex2Asm.java:406)
	at com.googlecode.d2j.dex.Dex2Asm.convertDex(Dex2Asm.java:422)
	at com.googlecode.d2j.dex.Dex2jar.doTranslate(Dex2jar.java:172)
	at com.googlecode.d2j.dex.Dex2jar.to(Dex2jar.java:272)
	at com.googlecode.dex2jar.tools.Dex2jarCmd.doCommandLine(Dex2jarCmd.java:108)
	at com.googlecode.dex2jar.tools.BaseCmd.doMain(BaseCmd.java:288)
	at com.googlecode.dex2jar.tools.Dex2jarCmd.main(Dex2jarCmd.java:32)
Caused by: java.lang.NullPointerException
	at com.googlecode.dex2jar.ir.ts.UnSSATransformer$LiveA.onUseLocal(UnSSATransformer.java:552)
	at com.googlecode.dex2jar.ir.ts.UnSSATransformer$LiveA.onUseLocal(UnSSATransformer.java:1)
	at com.googlecode.dex2jar.ir.ts.an.BaseAnalyze.onUse(BaseAnalyze.java:166)
	at com.googlecode.dex2jar.ir.ts.an.BaseAnalyze.onUse(BaseAnalyze.java:1)
	at com.googlecode.dex2jar.ir.ts.Cfg.travel(Cfg.java:331)
	at com.googlecode.dex2jar.ir.ts.Cfg.travel(Cfg.java:387)
	at com.googlecode.dex2jar.ir.ts.an.BaseAnalyze.exec(BaseAnalyze.java:90)
	... 17 more
.method private final a(Ljava/util/List;)Lcom/douban/insight/model/FullReport;
    .annotation system Ldalvik/annotation/Signature;
        value = {
            "(",
            "Ljava/util/List",
            "<+",
            "Lcom/douban/insight/model/Report;",
            ">;)",
            "Lcom/douban/insight/model/FullReport;"
        }
    .end annotation
    .registers 8
    sget-object v0, Lcom/douban/insight/Utilities;->a:Lcom/douban/insight/Utilities;
    iget-object v1, p0, Lcom/douban/insight/ReportGenerator;->g:Landroid/content/Context;
    iget-object v0, p0, Lcom/douban/insight/ReportGenerator;->f:Lcom/douban/insight/ReportGenerator$listener$1;
    check-cast v0, Landroid/location/LocationListener;
    invoke-static { v1, v0 }, Lcom/douban/insight/Utilities;->b(Landroid/content/Context;Landroid/location/LocationListener;)V
    const/4 v0, 0
    iput-boolean v0, p0, Lcom/douban/insight/ReportGenerator;->a:Z
    new-instance v2, Lcom/douban/insight/model/FullReport;
    invoke-static { }, Ljava/lang/System;->currentTimeMillis()J
    move-result-wide v0
    iget-wide v4, p0, Lcom/douban/insight/ReportGenerator;->d:J
    sub-long/2addr v0, v4
    if-nez p1, :L3
    invoke-static { }, Lkotlin/collections/CollectionsKt;->a()Ljava/util/List;
    move-result-object p1
    move-object v3, v2
    :L0
    invoke-direct { v2, v0, v1, p1 }, Lcom/douban/insight/model/FullReport;-><init>(JLjava/util/List;)V
    iget-object v0, p0, Lcom/douban/insight/ReportGenerator;->k:Lcom/douban/insight/NetInsight$Callback;
    if-eqz v0, :L1
    invoke-interface { v0, v3 }, Lcom/douban/insight/NetInsight$Callback;->a(Lcom/douban/insight/model/FullReport;)V
    :L1
    invoke-static { }, Lcom/douban/insight/NetInsight;->c()Z
    move-result v0
    if-eqz v0, :L2
    const-string/jumbo v0, "NetInsight"
    new-instance v1, Ljava/lang/StringBuilder;
    const-string/jumbo v2, "generateReport end at "
    invoke-direct { v1, v2 }, Ljava/lang/StringBuilder;-><init>(Ljava/lang/String;)V
    sget-object v2, Lcom/douban/insight/Utilities;->a:Lcom/douban/insight/Utilities;
    invoke-virtual { v2 }, Lcom/douban/insight/Utilities;->a()Ljava/lang/String;
    move-result-object v2
    invoke-virtual { v1, v2 }, Ljava/lang/StringBuilder;->append(Ljava/lang/String;)Ljava/lang/StringBuilder;
    move-result-object v1
    invoke-virtual { v1 }, Ljava/lang/StringBuilder;->toString()Ljava/lang/String;
    move-result-object v1
    invoke-static { v0, v1 }, Landroid/util/Log;->d(Ljava/lang/String;Ljava/lang/String;)I
    :L2
    return-object v3
    :L3
    move-object v3, v2
    goto :L0
.end method

**Comment by Biswa96** [comment]
May you provide the .jar file link?
