### ISSUE TITLE
Usage of dex2jar programmatically

### ISSUE THREAD

**Issue by ZEPORATH** [pxb1988/dex2jar#159]
Hi, this may be stupid but can I be pointed out, about how to supply .apk path and use d2j-smali to use fetch the smali files in output  folder.
A simple example would be great.
Any help is highly appreciated.

**Comment by ZEPORATH** [comment]
I've added these lines in my android-project but now facing new runtime-error:
` try {
            Baksmali b = Baksmali.from(dex);
            b.to(outputPath);
        }catch (IOException e){
            Log.d("error",e.getMessage());
        }`

The error are: 
` E/AndroidRuntime: FATAL EXCEPTION: main
                                                                           Process: com.smalitoscore.research, PID: 13131
                                                                           java.lang.NoSuchMethodError: No virtual method toPath()Ljava/nio/file/Path; in class Ljava/io/File; or its super classes (declaration of 'java.io.File' appears in /system/framework/core-oj.jar)
                                                                               at com.googlecode.d2j.reader.zip.ZipUtil.readDex(ZipUtil.java:53)
                                                                               at com.googlecode.d2j.smali.Baksmali.from(Baksmali.java:45)
                                                                               at com.smalitoscore.research.MainActivity.packageDetails(MainActivity.java:87)
                                                                               at com.smalitoscore.research.MainActivity.onCreate(MainActivity.java:59)
                                                                               at android.app.Activity.performCreate(Activity.java:6679)
                                                                               at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1118)
                                                                               at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2618)
                                                                               at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2726)
                                                                               at android.app.ActivityThread.-wrap12(ActivityThread.java)
                                                                               at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1477)
                                                                               at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                               at android.os.Looper.loop(Looper.java:154)
                                                                               at android.app.ActivityThread.main(ActivityThread.java:6119)
                                                                               at java.lang.reflect.Method.invoke(Native Method)
                                                                               at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
                                                                               at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
`

Its just an attempt to know working of dex2jar so I started experimenting in MainActivity.java itself

**Comment by greyblue9** [comment]
Are you on a KitKat device (or maybe Lollipop)? I've run into this also.
The framework (on-phone class library) doesn't have the "NIO.2" classes
like the whole "java.nio.file." package. It's part of Java 7, so many
projects are using it as a quick way to get a file opened or manipulate
paths.

I had to find all the uses of java.nio.file.{Files, Path, Paths}, and
change those lines to use the older (and present on older Android)
"java.io.File" and "java.net.URI" classes instead. For example,
  outputDirFile.toPath()  <--  toPath() added to java.io.File class late
(NIO.2+ only)
  A string is all that's often needed. There are some simple
java.nio.file.Path / java.nio.file.Files backports as well.

Hope that helps.
--David.

**Comment by ZEPORATH** [comment]
Yes, I think that is what I've to opt for, my app builds correctly for ` minSdkVersion 27
`, which is not good, and therefore change the usages.
