### ISSUE TITLE
While using DexReader.java class it gives not support version error

### ISSUE THREAD

**Issue by shashankd** [pxb1988/dex2jar#205]
Using gradle 4.4 and Android Studio 3.1.3 to create apk 
Android SDK 27

```
com.googlecode.d2j.DexException: not support version.
        at com.googlecode.d2j.reader.DexFileReader.<init>(DexFileReader.java:148)
        at com.googlecode.d2j.reader.DexFileReader.<init>(DexFileReader.java:208)
        at com.googlecode.d2j.reader.DexFileReader.<init>(DexFileReader.java:222)
        at com.googlecode.d2j.reader.DexFileReader.<init>(DexFileReader.java:218)
        at com.ibm.haac.mac.instrumentation.Dex2JarWrapper.dex2jar(Dex2JarWrapper.java:73)
        at com.ibm.haac.mac.driver.ServerDriver.generateA11yApk(ServerDriver.java:216)
        at com.ibm.haac.accessibility_plugin_cmd.Main.runAndroid(Main.java:106)
        at com.ibm.haac.accessibility_plugin_cmd.Main.main(Main.java:34)
dex2jar completed for D:\MAC\MAC-Android-Test\AppiumTestJS\_Generated\TestApk\classes.dex
com.googlecode.d2j.DexException: not support version.
        at com.googlecode.d2j.reader.DexFileReader.<init>(DexFileReader.java:148)
        at com.googlecode.d2j.reader.DexFileReader.<init>(DexFileReader.java:208)
        at com.googlecode.d2j.reader.DexFileReader.<init>(DexFileReader.java:222)
        at com.googlecode.d2j.reader.DexFileReader.<init>(DexFileReader.java:218)
        at com.ibm.haac.mac.instrumentation.Dex2JarWrapper.dex2jar(Dex2JarWrapper.java:73)
        at com.ibm.haac.mac.driver.ServerDriver.generateA11yApk(ServerDriver.java:216)
        at com.ibm.haac.accessibility_plugin_cmd.Main.runAndroid(Main.java:106)
        at com.ibm.haac.accessibility_plugin_cmd.Main.main(Main.java:34)
```

Dex2JarWrapper,java creates new instance of DexFileReader.
`DexFileReader reader = new DexFileReader(srcDex);`

**Comment by nickma82** [comment]
Please take a look at this: https://github.com/pxb1988/dex2jar/issues/93#issuecomment-333352525 in thread https://github.com/pxb1988/dex2jar/issues/205, they seem to have the same problem.
