### ISSUE TITLE
Dex2jar has problem with Gradle 4.4

### ISSUE THREAD

**Issue by duanjason** [pxb1988/dex2jar#207]
We use dex2jar to manipulate apk files generated by Android Studio. It has been working as expected until recently with projects built with Gradle version 4.4. 

I coded a very simple app to debug this issue. The app has a text field and a label. Below is the steps to recreate the problem.

- run the application in Android Studio, find the apk in the build folder...
- run Dex2jar command to convert the apk to dex.  

        Dex2jarCmd app-debug.apk -o app-debug.jar

- run Jar2Dex to convert the jar back to dex.

        Jar2Dex app-debug.jar -o classes.dex

- I have some code to take the dex and use apktool to package it into an apk file.
- install and run the apk on emulator.

If the Gradle version of my project is set to 3.0.0 or 4.1, then the new apk works fine. If the Gradle version of the project is set to 4.4, then the app will fail when it starts in the emulator with errors below.

This is for our production system. Can someone please look into this as soon as possible or provide some hints to debug and fix it?

Thanks.

---------
08-08 12:20:50.468 12695-12695/? I/zygote: Not late-enabling -Xcheck:jni (already on)
08-08 12:20:50.483 12695-12695/? W/zygote: Unexpected CPU variant for X86 using defaults: x86
08-08 12:20:50.517 12695-12702/? E/zygote: Failed sending reply to debugger: Broken pipe
08-08 12:20:50.517 12695-12702/? I/zygote: Debugger is no longer active
08-08 12:20:50.545 12695-12695/? W/zygote: Class android.support.v4.util.SimpleArrayMap failed lock verification and will run slower.
    Common causes for lock verification issues are non-optimized dex code
    and incorrect proguard optimizations.
08-08 12:20:50.550 12695-12695/? W/zygote: Class android.support.v4.content.ContextCompat failed lock verification and will run slower.
08-08 12:20:50.609 12695-12711/? D/OpenGLRenderer: HWUI GL Pipeline
08-08 12:20:50.633 12695-12695/? D/AndroidRuntime: Shutting down VM
    
    
    --------- beginning of crash
08-08 12:20:50.634 12695-12695/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.example.jasonxd.android_demo1, PID: 12695
    java.lang.ArrayIndexOutOfBoundsException: src.length=4 srcPos=-1 dst.length=4 dstPos=0 length=1
        at java.lang.System.arraycopy(Native Method)
        at android.support.v4.util.SimpleArrayMap.put(Unknown Source:95)
        at android.support.design.widget.DirectedAcyclicGraph.addNode(Unknown Source:11)
        at android.support.design.widget.CoordinatorLayout.prepareChildren(Unknown Source:31)
        at android.support.design.widget.CoordinatorLayout.onMeasure(Unknown Source:0)
        at android.view.View.measure(View.java:22002)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6580)
        at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
        at android.support.v7.widget.ContentFrameLayout.onMeasure(Unknown Source:125)
        at android.view.View.measure(View.java:22002)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6580)
        at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1514)
        at android.widget.LinearLayout.measureVertical(LinearLayout.java:806)
        at android.widget.LinearLayout.onMeasure(LinearLayout.java:685)
        at android.view.View.measure(View.java:22002)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6580)
        at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
        at android.view.View.measure(View.java:22002)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6580)
        at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1514)
        at android.widget.LinearLayout.measureVertical(LinearLayout.java:806)
        at android.widget.LinearLayout.onMeasure(LinearLayout.java:685)
        at android.view.View.measure(View.java:22002)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6580)
        at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
        at com.android.internal.policy.DecorView.onMeasure(DecorView.java:721)
        at android.view.View.measure(View.java:22002)
        at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:2410)
        at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:1498)
        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1751)
        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1386)
        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6733)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:911)
        at android.view.Choreographer.doCallbacks(Choreographer.java:723)
        at android.view.Choreographer.doFrame(Choreographer.java:658)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:897)
        at android.os.Handler.handleCallback(Handler.java:789)
        at android.os.Handler.dispatchMessage(Handler.java:98)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6541)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)

**Comment by duanjason** [comment]
I narrowed down the issue. The problem is Dex2Jar doesn't handle code built by Gradle 4.4 that contains bitwise operator `~` properly. The `~` operator is gone in the decompiled code.

Anyone has idea which part of the code handle this?

**Comment by bensh** [comment]
Further to this, It seems to not work with anything over 3.0.0?
I just built a project with 3.1.2 and it failed.

Hope this can be fixed soon, its been an issue for months

**Comment by duanjason** [comment]
@bensh I think the issue is Dex2Jar has problem to handle code generated by the new D8 dx engine. I find that the ~ bitwise complement operator is compiled into IXOR -1 with the older engine, but the D8 compiles it into NOT-INT. NOT-INT is not a Java bytecode instruction. So, it fails.

I wonder if the owner of this project aware of the issue and if there is any plan to update it to support the D8 engine. I have not seen much activity on the project.

**Comment by yudhabotemz** [comment]
Great.. 
convert to dex, convert back to jar and convert again to dex methods really work for me to fix "// INTERNAL ERROR //"

thanks alot

**Comment by vramasam** [comment]
@duanjason Did you get any resolution for this issue?

**Comment by bensh** [comment]
Unfortunately it seems dex2jar is dead. Its not been updated in years. Switch to a better supported tool such as JadX or enjarify. Such a shame.

**Comment by vramasam** [comment]
@echooo10 Patch given by you, worked for me. Thank you

**Comment by duanjason** [comment]
@vramasam No, I don't have any resolution.

**Comment by echooo10** [comment]
@vramasam You're welcome. Thanks to @duanjason for locating the problem, it helps me a lot.

**Comment by geilige** [comment]
java.lang.StringIndexOutOfBoundsException: String index out of range: -2
	at java.lang.String.substring(String.java:1967)
	at org.objectweb.asm.signature.SignatureReader.parseType(SignatureReader.java:169)
	at org.objectweb.asm.signature.SignatureReader.acceptType(SignatureReader.java:130)
	at org.objectweb.asm.commons.Remapper.mapSignature(Remapper.java:162)
	at org.objectweb.asm.commons.RemappingClassAdapter.visitField(RemappingClassAdapter.java:90)
	at org.objectweb.asm.ClassVisitor.visitField(ClassVisitor.java:272)
	at com.googlecode.d2j.dex.Dex2Asm.convertField(Dex2Asm.java:488)
	at com.googlecode.d2j.dex.Dex2Asm.convertClass(Dex2Asm.java:439)
	at com.googlecode.d2j.dex.Dex2Asm.convertClass(Dex2Asm.java:357)
	at com.googlecode.d2j.dex.Dex2Asm.convertDex(Dex2Asm.java:460)
	at com.googlecode.d2j.dex.Dex2jar.doTranslate(Dex2jar.java:175)
	at com.googlecode.d2j.dex.Dex2jar.to(Dex2jar.java:275)
	at com.googlecode.dex2jar.tools.Dex2jarCmd.doCommandLine(Dex2jarCmd.java:112)
	at com.googlecode.dex2jar.tools.BaseCmd.doMain(BaseCmd.java:290)
	at com.googlecode.dex2jar.tools.Dex2jarCmd.main(Dex2jarCmd.java:33)
