### ISSUE TITLE
Throw exception: java.io.IOException: cant find zipfs support, on android O Device

### ISSUE THREAD

**Issue by WindySha** [pxb1988/dex2jar#241]
When I run dex2jar codes on android device(sunsang S8, android O), I got this error, I don't know how to fix this. I hope to get some help. Thank you so much.

```
019-01-13 00:56:10.030 26610-26671/com.storm.wind.buldjarproject W/System.err: dex2jar /storage/emulated/0/classes.dex -> /storage/emulated/0/classes-dex2jar.jar
2019-01-13 00:56:10.040 26610-26675/com.storm.wind.buldjarproject D/OpenGLRenderer: HWUI GL Pipeline
2019-01-13 00:56:10.055 26610-26610/com.storm.wind.buldjarproject D/ViewRootImpl@48cf6ba[MainActivity]: setView = DecorView@10de96b[MainActivity] TM=true MM=false
2019-01-13 00:56:10.057 26610-26671/com.storm.wind.buldjarproject W/System.err: xiwanli , scheme = file
2019-01-13 00:56:10.057 26610-26671/com.storm.wind.buldjarproject W/System.err: java.io.IOException: cant find zipfs support
2019-01-13 00:56:10.057 26610-26671/com.storm.wind.buldjarproject W/System.err:     at com.googlecode.d2j.dex.Dex2jar.createZip(Dex2jar.java:348)
2019-01-13 00:56:10.057 26610-26671/com.storm.wind.buldjarproject W/System.err:     at com.googlecode.d2j.dex.Dex2jar.to(Dex2jar.java:327)
2019-01-13 00:56:10.058 26610-26671/com.storm.wind.buldjarproject W/System.err:     at com.googlecode.dex2jar.tools.Dex2jarCmd.doCommandLine(Dex2jarCmd.java:112)
2019-01-13 00:56:10.058 26610-26671/com.storm.wind.buldjarproject W/System.err:     at com.googlecode.dex2jar.tools.BaseCmd.doMain(BaseCmd.java:293)
2019-01-13 00:56:10.058 26610-26671/com.storm.wind.buldjarproject W/System.err:     at com.googlecode.dex2jar.tools.Dex2jarCmd.main(Dex2jarCmd.java:33)
2019-01-13 00:56:10.058 26610-26671/com.storm.wind.buldjarproject W/System.err:     at com.storm.wind.buldjarproject.MainActivity$1.run(MainActivity.java:60)
2019-01-13 00:56:10.058 26610-26671/com.storm.wind.buldjarproject W/System.err:     at java.lang.Thread.run(Thread.java:764)
```

**Comment by pxb1988** [comment]
please get the zipfs support from java-11 source tree, register the FileSystem before running dex2jar
