### ISSUE TITLE
20 methods fail to translate

### ISSUE THREAD

**Issue by Hongzheng-Li** [pxb1988/dex2jar#25]
There are 20 methods fail to translate.
2015-08-23 17:47:05 UTC
version: [dex-reader-2.0, dex-reader-api-2.0, dex-ir-2.0, d2j-smali-2.0, d2j-base-cmd-2.0, dex-tools-2.0, dex-translator-2.0]
cmdline: []
env:
java.runtime.name: Java(TM) SE Runtime Environment
java.vm.version: 24.65-b04
java.vm.vendor: Oracle Corporation
java.vendor.url: http://java.oracle.com/
java.vm.name: Java HotSpot(TM) 64-Bit Server VM
java.vm.specification.name: Java Virtual Machine Specification
java.runtime.version: 1.7.0_65-b19
java.awt.graphicsenv: sun.awt.Win32GraphicsEnvironment
java.endorsed.dirs: C:\Program Files\Java\jdk1.7.0_65\jre\lib\endorsed
java.io.tmpdir: C:\Users\HONGZH~1\AppData\Local\Temp\
java.vm.specification.vendor: Oracle Corporation
java.library.path: C:\Program Files\Java\jdk1.7.0_65\bin;C:\Windows\Sun\Java\bin;C:\Windows\system32;C:\Windows;C:\Program Files\Java\jdk1.7.0_65\bin;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files\TortoiseSVN\bin;C:\Program Files\TortoiseGit\bin;D:\apache-maven-3.2.2\bin;D:\android-sdks\tools;C:\Program Files\Common Files\Lenovo;C:\Program Files (x86)\Skype\Phone\;D:\gradle-2.6\bin;C:\Program Files (x86)\SSH Communications Security\SSH Secure Shell;.
java.specification.name: Java Platform API Specification
java.class.version: 51.0
java.awt.printerjob: sun.awt.windows.WPrinterJob
java.specification.version: 1.7
java.class.path: E:\Android\tools\dex2jar-2.0\lib\antlr-runtime-3.5.jar;E:\Android\tools\dex2jar-2.0\lib\asm-debug-all-4.1.jar;E:\Android\tools\dex2jar-2.0\lib\d2j-base-cmd-2.0.jar;E:\Android\tools\dex2jar-2.0\lib\d2j-jasmin-2.0.jar;E:\Android\tools\dex2jar-2.0\lib\d2j-smali-2.0.jar;E:\Android\tools\dex2jar-2.0\lib\dex-ir-2.0.jar;E:\Android\tools\dex2jar-2.0\lib\dex-reader-2.0.jar;E:\Android\tools\dex2jar-2.0\lib\dex-reader-api-2.0.jar;E:\Android\tools\dex2jar-2.0\lib\dex-tools-2.0.jar;E:\Android\tools\dex2jar-2.0\lib\dex-translator-2.0.jar;E:\Android\tools\dex2jar-2.0\lib\dex-writer-2.0.jar;E:\Android\tools\dex2jar-2.0\lib\dx-1.7.jar;
java.vm.specification.version: 1.7
java.home: C:\Program Files\Java\jdk1.7.0_65\jre
java.specification.vendor: Oracle Corporation
java.vm.info: mixed mode
java.version: 1.7.0_65
java.ext.dirs: C:\Program Files\Java\jdk1.7.0_65\jre\lib\ext;C:\Windows\Sun\Java\lib\ext
java.vendor: Oracle Corporation
java.vendor.url.bug: http://bugreport.sun.com/bugreport/

**Comment by Hongzheng-Li** [comment]
m-0.txt
Landroid/support/v4/widget/ScrollerCompatGingerbread;.createScroller(Landroid/content/Context;Landroid/view/animation/Interpolator;)Ljava/lang/Object;
java.lang.RuntimeException: fail exe a3 = a2
    at com.googlecode.dex2jar.ir.ts.an.BaseAnalyze.exec(BaseAnalyze.java:92)
    at com.googlecode.dex2jar.ir.ts.an.BaseAnalyze.exec(BaseAnalyze.java:1)
    at com.googlecode.dex2jar.ir.ts.Cfg.dfs(Cfg.java:255)
    at com.googlecode.dex2jar.ir.ts.an.BaseAnalyze.analyze0(BaseAnalyze.java:75)
    at com.googlecode.dex2jar.ir.ts.an.BaseAnalyze.analyze(BaseAnalyze.java:69)
    at com.googlecode.dex2jar.ir.ts.UnSSATransformer.transform(UnSSATransformer.java:274)
    at com.googlecode.d2j.dex.Dex2jar$2.optimize(Dex2jar.java:163)
    at com.googlecode.d2j.dex.Dex2Asm.convertCode(Dex2Asm.java:414)
    at com.googlecode.d2j.dex.ExDex2Asm.convertCode(ExDex2Asm.java:42)
    at com.googlecode.d2j.dex.Dex2jar$2.convertCode(Dex2jar.java:128)
    at com.googlecode.d2j.dex.Dex2Asm.convertMethod(Dex2Asm.java:509)
    at com.googlecode.d2j.dex.Dex2Asm.convertClass(Dex2Asm.java:406)
    at com.googlecode.d2j.dex.Dex2Asm.convertDex(Dex2Asm.java:422)
    at com.googlecode.d2j.dex.Dex2jar.doTranslate(Dex2jar.java:172)
    at com.googlecode.d2j.dex.Dex2jar.to(Dex2jar.java:272)
    at com.googlecode.dex2jar.tools.Dex2jarCmd.doCommandLine(Dex2jarCmd.java:108)
    at com.googlecode.dex2jar.tools.BaseCmd.doMain(BaseCmd.java:288)
    at com.googlecode.dex2jar.tools.Dex2jarCmd.main(Dex2jarCmd.java:32)
Caused by: java.lang.NullPointerException
    at com.googlecode.dex2jar.ir.ts.UnSSATransformer$LiveA.onUseLocal(UnSSATransformer.java:552)
    at com.googlecode.dex2jar.ir.ts.UnSSATransformer$LiveA.onUseLocal(UnSSATransformer.java:1)
    at com.googlecode.dex2jar.ir.ts.an.BaseAnalyze.onUse(BaseAnalyze.java:166)
    at com.googlecode.dex2jar.ir.ts.an.BaseAnalyze.onUse(BaseAnalyze.java:1)
    at com.googlecode.dex2jar.ir.ts.Cfg.travel(Cfg.java:331)
    at com.googlecode.dex2jar.ir.ts.Cfg.travel(Cfg.java:387)
    at com.googlecode.dex2jar.ir.ts.an.BaseAnalyze.exec(BaseAnalyze.java:90)
    ... 17 more

.method public static createScroller(Landroid/content/Context;Landroid/view/animation/Interpolator;)Ljava/lang/Object;
    .registers 9
    move-object v0, p0
    move-object v1, p1
    move-object v2, v1
    if-eqz v2, :L1
    new-instance v2, Landroid/widget/OverScroller;
    move-object v6, v2
    move-object v2, v6
    move-object v3, v6
    move-object v4, v0
    move-object v5, v1
    invoke-direct { v3, v4, v5 }, Landroid/widget/OverScroller;-><init>(Landroid/content/Context;Landroid/view/animation/Interpolator;)V
    :L0
    move-object v0, v2
    return-object v0
    :L1
    new-instance v2, Landroid/widget/OverScroller;
    move-object v6, v2
    move-object v2, v6
    move-object v3, v6
    move-object v4, v0
    invoke-direct { v3, v4 }, Landroid/widget/OverScroller;-><init>(Landroid/content/Context;)V
    goto :L0
.end method

**Comment by Hongzheng-Li** [comment]
m-1.txt
Lcom/google/gson/JsonObject;.createJsonElement(Ljava/lang/Object;)Lcom/google/gson/JsonElement;
java.lang.RuntimeException: fail exe a5 = a4
    at com.googlecode.dex2jar.ir.ts.an.BaseAnalyze.exec(BaseAnalyze.java:92)
    at com.googlecode.dex2jar.ir.ts.an.BaseAnalyze.exec(BaseAnalyze.java:1)
    at com.googlecode.dex2jar.ir.ts.Cfg.dfs(Cfg.java:255)
    at com.googlecode.dex2jar.ir.ts.an.BaseAnalyze.analyze0(BaseAnalyze.java:75)
    at com.googlecode.dex2jar.ir.ts.an.BaseAnalyze.analyze(BaseAnalyze.java:69)
    at com.googlecode.dex2jar.ir.ts.UnSSATransformer.transform(UnSSATransformer.java:274)
    at com.googlecode.d2j.dex.Dex2jar$2.optimize(Dex2jar.java:163)
    at com.googlecode.d2j.dex.Dex2Asm.convertCode(Dex2Asm.java:414)
    at com.googlecode.d2j.dex.ExDex2Asm.convertCode(ExDex2Asm.java:42)
    at com.googlecode.d2j.dex.Dex2jar$2.convertCode(Dex2jar.java:128)
    at com.googlecode.d2j.dex.Dex2Asm.convertMethod(Dex2Asm.java:509)
    at com.googlecode.d2j.dex.Dex2Asm.convertClass(Dex2Asm.java:406)
    at com.googlecode.d2j.dex.Dex2Asm.convertDex(Dex2Asm.java:422)
    at com.googlecode.d2j.dex.Dex2jar.doTranslate(Dex2jar.java:172)
    at com.googlecode.d2j.dex.Dex2jar.to(Dex2jar.java:272)
    at com.googlecode.dex2jar.tools.Dex2jarCmd.doCommandLine(Dex2jarCmd.java:108)
    at com.googlecode.dex2jar.tools.BaseCmd.doMain(BaseCmd.java:288)
    at com.googlecode.dex2jar.tools.Dex2jarCmd.main(Dex2jarCmd.java:32)
Caused by: java.lang.NullPointerException
    at com.googlecode.dex2jar.ir.ts.UnSSATransformer$LiveA.onUseLocal(UnSSATransformer.java:552)
    at com.googlecode.dex2jar.ir.ts.UnSSATransformer$LiveA.onUseLocal(UnSSATransformer.java:1)
    at com.googlecode.dex2jar.ir.ts.an.BaseAnalyze.onUse(BaseAnalyze.java:166)
    at com.googlecode.dex2jar.ir.ts.an.BaseAnalyze.onUse(BaseAnalyze.java:1)
    at com.googlecode.dex2jar.ir.ts.Cfg.travel(Cfg.java:331)
    at com.googlecode.dex2jar.ir.ts.Cfg.travel(Cfg.java:387)
    at com.googlecode.dex2jar.ir.ts.an.BaseAnalyze.exec(BaseAnalyze.java:90)
    ... 17 more

.method private createJsonElement(Ljava/lang/Object;)Lcom/google/gson/JsonElement;
    .registers 8
    move-object v0, p0
    move-object v1, p1
    move-object v2, v1
    if-nez v2, :L1
    sget-object v2, Lcom/google/gson/JsonNull;->INSTANCE:Lcom/google/gson/JsonNull;
    :L0
    move-object v0, v2
    return-object v0
    :L1
    new-instance v2, Lcom/google/gson/JsonPrimitive;
    move-object v5, v2
    move-object v2, v5
    move-object v3, v5
    move-object v4, v1
    invoke-direct { v3, v4 }, Lcom/google/gson/JsonPrimitive;-><init>(Ljava/lang/Object;)V
    goto :L0
.end method

**Comment by pxb1988** [comment]
similar with #4 , could you please try the nightly build here
https://github.com/pxb1988/dex2jar/releases/tag/2.1-nightly-26

**Comment by Hongzheng-Li** [comment]
I have tried the newest dex2jar, and issue disappears, thank you very much.

**Comment by OuIChien** [comment]
Do not work for me

**Comment by wuyinghandong** [comment]
Do not work for me too

**Comment by maxmastalerz** [comment]
Also having a similar issue:

There are 86 methods fail to translate.
2021-03-25 03:07:22 UTC
version: [dex-reader-2.0, dex-reader-api-2.0, dex-ir-2.0, d2j-smali-2.0, d2j-base-cmd-2.0, dex-tools-2.0, dex-translator-2.0]
cmdline: [classes.dex]
env:
java.specification.version: 11
java.class.path: .:./lib/antlr-runtime-3.5.jar:./lib/asm-debug-all-4.1.jar:./lib/d2j-base-cmd-2.0.jar:./lib/d2j-jasmin-2.0.jar:./lib/d2j-smali-2.0.jar:./lib/dex-ir-2.0.jar:./lib/dex-reader-2.0.jar:./lib/dex-reader-api-2.0.jar:./lib/dex-tools-2.0.jar:./lib/dex-translator-2.0.jar:./lib/dex-writer-2.0.jar:./lib/dx-1.7.jar
java.vm.vendor: Ubuntu
java.vendor.url: https://ubuntu.com/
java.vm.specification.version: 11
java.specification.vendor: Oracle Corporation
java.version.date: 2021-01-19
java.home: /usr/lib/jvm/java-11-openjdk-amd64
java.vm.compressedOopsMode: 32-bit
java.specification.name: Java Platform API Specification
java.vm.specification.vendor: Oracle Corporation
java.awt.graphicsenv: sun.awt.X11GraphicsEnvironment
java.runtime.version: 11.0.10+9-Ubuntu-0ubuntu1.20.04
java.runtime.name: OpenJDK Runtime Environment
java.vm.name: OpenJDK 64-Bit Server VM
java.vendor.url.bug: https://bugs.launchpad.net/ubuntu/+source/openjdk-lts
java.io.tmpdir: /tmp
java.version: 11.0.10
java.vm.specification.name: Java Virtual Machine Specification
java.awt.printerjob: sun.print.PSPrinterJob
java.library.path: /usr/java/packages/lib:/usr/lib/x86_64-linux-gnu/jni:/lib/x86_64-linux-gnu:/usr/lib/x86_64-linux-gnu:/usr/lib/jni:/lib:/usr/lib
java.vm.info: mixed mode, sharing
java.vendor: Ubuntu
java.vm.version: 11.0.10+9-Ubuntu-0ubuntu1.20.04
java.class.version: 55.0

**Comment by code4happylife** [comment]
Thank you for your guidance.
https://github.com/pxb1988/dex2jar/releases/tag/2.1-nightly-26
