### ISSUE TITLE
d2j-smali : java.nio.charset.MalformedInputException: Input length = 1

### ISSUE THREAD

**Issue by javaeryang** [pxb1988/dex2jar#253]
➜  dex2jar-2.0 ./d2j-smali.sh -o /Users/javaer/Documents/Javaer/xposed.dex -a 14 /Users/javaer/Documents/Javaer/xp/*
smali /Users/javaer/Documents/Javaer/xp/android -> /Users/javaer/Documents/Javaer/xposed.dex
smali /Users/javaer/Documents/Javaer/xp/de -> /Users/javaer/Documents/Javaer/xposed.dex
java.nio.charset.MalformedInputException: Input length = 1
	at java.nio.charset.CoderResult.throwException(CoderResult.java:281)
	at sun.nio.cs.StreamDecoder.implRead(StreamDecoder.java:339)
	at sun.nio.cs.StreamDecoder.read(StreamDecoder.java:178)
	at java.io.InputStreamReader.read(InputStreamReader.java:184)
	at java.io.BufferedReader.fill(BufferedReader.java:161)
	at java.io.BufferedReader.read1(BufferedReader.java:212)
	at java.io.BufferedReader.read(BufferedReader.java:286)
	at org.antlr.runtime.ANTLRReaderStream.load(ANTLRReaderStream.java:82)
	at org.antlr.runtime.ANTLRReaderStream.<init>(ANTLRReaderStream.java:53)
	at org.antlr.runtime.ANTLRReaderStream.<init>(ANTLRReaderStream.java:45)
	at com.googlecode.d2j.smali.Smali.smaliFile(Smali.java:40)
	at com.googlecode.d2j.smali.Smali$1.visitFile(Smali.java:87)
	at com.googlecode.d2j.smali.Smali$1.visitFile(Smali.java:1)
	at java.nio.file.Files.walkFileTree(Files.java:2670)
	at java.nio.file.Files.walkFileTree(Files.java:2742)
	at com.googlecode.d2j.smali.Smali.smali(Smali.java:75)
	at com.googlecode.d2j.smali.SmaliCmd.doCommandLine(SmaliCmd.java:68)
	at com.googlecode.dex2jar.tools.BaseCmd.doMain(BaseCmd.java:288)
	at com.googlecode.d2j.smali.SmaliCmd.main(SmaliCmd.java:26)

**Comment by vickyleu** [comment]
我也是

**Comment by p2kyc0ng** [comment]
![image](https://github.com/pxb1988/dex2jar/assets/48485920/26683286-a02c-446b-898c-98686ee21aa4)
same

**Comment by headfirst123** [comment]
你的来信已收到，谢谢

**Comment by ThexXTURBOXx** [comment]
@headfirst123 You might want to turn this off. You are somehow automatically replying to every comment in this repo.

@park671 Have you tried my fork?

**Comment by p2kyc0ng** [comment]
@ThexXTURBOXx  thx, i will try it next time when i need d2j

**Comment by yunylz** [comment]
still occurs

**Comment by yunylz** [comment]
> @headfirst123 You might want to turn this off. You are somehow automatically replying to every comment in this repo.
> 
> @park671 Have you tried my fork?

its still the same with ur fork
