### ISSUE TITLE
There are 1 methods fail to translate.(Caused by: java.lang.NullPointerException)

### ISSUE THREAD

**Issue by Dan8312** [pxb1988/dex2jar#277]
#This file is generated by dex2jar
Please report this file to one of following link if possible (any one).
    https://sourceforge.net/p/dex2jar/tickets/
    https://bitbucket.org/pxb1988/dex2jar/issues
    https://github.com/pxb1988/dex2jar/issues
    dex2jar@googlegroups.com

There are 1 methods fail to translate.
2019-05-21 02:56:00 UTC
version: [dex-reader-2.1-SNAPSHOT, dex-reader-api-2.1-SNAPSHOT, dex-ir-2.1-SNAPSHOT, d2j-smali-2.1-SNAPSHOT, d2j-base-cmd-2.1-SNAPSHOT, dex-tools-2.1-SNAPSHOT, dex-translator-2.1-SNAPSHOT]
cmdline: [classes7.dex]
env:
java.runtime.name: Java(TM) SE Runtime Environment
java.vm.version: 25.162-b12
java.vm.vendor: Oracle Corporation
java.vendor.url: http://java.oracle.com/
java.vm.name: Java HotSpot(TM) 64-Bit Server VM
java.vm.specification.name: Java Virtual Machine Specification
java.runtime.version: 1.8.0_162-b12
java.awt.graphicsenv: sun.awt.CGraphicsEnvironment
java.endorsed.dirs: /Library/Java/JavaVirtualMachines/jdk1.8.0_151.jdk/Contents/Home/jre/lib/endorsed
java.io.tmpdir: /var/folders/jj/smvqjhdn45x9pwjh8vvlqccm0000gp/T/
java.vm.specification.vendor: Oracle Corporation
java.library.path: /Users/mobike/Library/Java/Extensions:/Library/Java/Extensions:/Network/Library/Java/Extensions:/System/Library/Java/Extensions:/usr/lib/java:.
java.specification.name: Java Platform API Specification
java.class.version: 52.0
java.awt.printerjob: sun.lwawt.macosx.CPrinterJob
java.specification.version: 1.8
java.class.path: .:./lib/ST4-4.0.8.jar:./lib/antlr-3.5.2.jar:./lib/antlr-runtime-3.5.2.jar:./lib/antlr4-4.5.jar:./lib/antlr4-runtime-4.5.jar:./lib/asm-debug-all-5.0.3.jar:./lib/d2j-base-cmd-2.1-SNAPSHOT.jar:./lib/d2j-jasmin-2.1-SNAPSHOT.jar:./lib/d2j-smali-2.1-SNAPSHOT.jar:./lib/dex-ir-2.1-SNAPSHOT.jar:./lib/dex-reader-2.1-SNAPSHOT.jar:./lib/dex-reader-api-2.1-SNAPSHOT.jar:./lib/dex-tools-2.1-SNAPSHOT.jar:./lib/dex-translator-2.1-SNAPSHOT.jar:./lib/dex-writer-2.1-SNAPSHOT.jar:./lib/dx-23.0.0.jar:./lib/org.abego.treelayout.core-1.0.1.jar
java.vm.specification.version: 1.8
java.home: /Library/Java/JavaVirtualMachines/jdk1.8.0_151.jdk/Contents/Home/jre
java.specification.vendor: Oracle Corporation
java.vm.info: mixed mode
java.version: 1.8.0_162
java.ext.dirs: /Users/mobike/Library/Java/Extensions:/Library/Java/JavaVirtualMachines/jdk1.8.0_151.jdk/Contents/Home/jre/lib/ext:/Library/Java/Extensions:/Network/Library/Java/Extensions:/System/Library/Java/Extensions:/usr/lib/java
java.vendor: Oracle Corporation
java.vendor.url.bug: http://bugreport.sun.com/bugreport/

================= 0 ===================
Lorg/mozilla/javascript/xmlimpl/XMLList;.call(Lorg/mozilla/javascript/Context;Lorg/mozilla/javascript/Scriptable;Lorg/mozilla/javascript/Scriptable;[Ljava/lang/Object;)Ljava/lang/Object;
java.lang.RuntimeException: fail exe a18 = a0
	at com.googlecode.dex2jar.ir.ts.an.BaseAnalyze.exec(BaseAnalyze.java:92)
	at com.googlecode.dex2jar.ir.ts.an.BaseAnalyze.exec(BaseAnalyze.java:31)
	at com.googlecode.dex2jar.ir.ts.Cfg.dfs(Cfg.java:255)
	at com.googlecode.dex2jar.ir.ts.an.BaseAnalyze.analyze0(BaseAnalyze.java:75)
	at com.googlecode.dex2jar.ir.ts.an.BaseAnalyze.analyze(BaseAnalyze.java:69)
	at com.googlecode.dex2jar.ir.ts.Ir2JRegAssignTransformer.transform(Ir2JRegAssignTransformer.java:182)
	at com.googlecode.d2j.dex.Dex2jar$2.optimize(Dex2jar.java:167)
	at com.googlecode.d2j.dex.Dex2Asm.convertCode(Dex2Asm.java:442)
	at com.googlecode.d2j.dex.ExDex2Asm.convertCode(ExDex2Asm.java:40)
	at com.googlecode.d2j.dex.Dex2jar$2.convertCode(Dex2jar.java:132)
	at com.googlecode.d2j.dex.Dex2Asm.convertMethod(Dex2Asm.java:575)
	at com.googlecode.d2j.dex.Dex2Asm.convertClass(Dex2Asm.java:434)
	at com.googlecode.d2j.dex.Dex2Asm.convertDex(Dex2Asm.java:450)
	at com.googlecode.d2j.dex.Dex2jar.doTranslate(Dex2jar.java:175)
	at com.googlecode.d2j.dex.Dex2jar.to(Dex2jar.java:275)
	at com.googlecode.dex2jar.tools.Dex2jarCmd.doCommandLine(Dex2jarCmd.java:112)
	at com.googlecode.dex2jar.tools.BaseCmd.doMain(BaseCmd.java:290)
	at com.googlecode.dex2jar.tools.Dex2jarCmd.main(Dex2jarCmd.java:33)
Caused by: java.lang.NullPointerException
	at com.googlecode.dex2jar.ir.ts.an.SimpleLiveAnalyze.onUseLocal(SimpleLiveAnalyze.java:89)
	at com.googlecode.dex2jar.ir.ts.an.SimpleLiveAnalyze.onUseLocal(SimpleLiveAnalyze.java:27)
	at com.googlecode.dex2jar.ir.ts.an.BaseAnalyze.onUse(BaseAnalyze.java:166)
	at com.googlecode.dex2jar.ir.ts.an.BaseAnalyze.onUse(BaseAnalyze.java:31)
	at com.googlecode.dex2jar.ir.ts.Cfg.travel(Cfg.java:331)
	at com.googlecode.dex2jar.ir.ts.Cfg.travel(Cfg.java:387)
	at com.googlecode.dex2jar.ir.ts.an.BaseAnalyze.exec(BaseAnalyze.java:90)
	... 17 more

.method public call(Lorg/mozilla/javascript/Context;Lorg/mozilla/javascript/Scriptable;Lorg/mozilla/javascript/Scriptable;[Ljava/lang/Object;)Ljava/lang/Object;
  .registers 13
    iget-object v0, p0, Lorg/mozilla/javascript/xmlimpl/XMLList;->targetProperty:Lorg/mozilla/javascript/xmlimpl/XmlNode$QName;
    if-eqz v0, :L7
    iget-object v0, p0, Lorg/mozilla/javascript/xmlimpl/XMLList;->targetProperty:Lorg/mozilla/javascript/xmlimpl/XmlNode$QName;
    invoke-virtual { v0 }, Lorg/mozilla/javascript/xmlimpl/XmlNode$QName;->getLocalName()Ljava/lang/String;
    move-result-object v0
    const-string v1, "apply"
    invoke-virtual { v0, v1 }, Ljava/lang/String;->equals(Ljava/lang/Object;)Z
    move-result v3
    if-nez v3, :L6
    const-string v1, "call"
    invoke-virtual { v0, v1 }, Ljava/lang/String;->equals(Ljava/lang/Object;)Z
    move-result v1
    if-eqz v1, :L0
    goto :L6
  :L0
    instance-of v1, p3, Lorg/mozilla/javascript/xml/XMLObject;
    if-eqz v1, :L5
    const/4 v1, 0
  :L1
    move-object v2, p3
  :L2
    instance-of v3, p3, Lorg/mozilla/javascript/xml/XMLObject;
    if-eqz v3, :L3
    check-cast p3, Lorg/mozilla/javascript/xml/XMLObject;
    invoke-virtual { p3, p1, v0 }, Lorg/mozilla/javascript/xml/XMLObject;->getFunctionProperty(Lorg/mozilla/javascript/Context;Ljava/lang/String;)Ljava/lang/Object;
    move-result-object v1
    sget-object v3, Lorg/mozilla/javascript/Scriptable;->NOT_FOUND:Ljava/lang/Object;
    if-ne v1, v3, :L3
    invoke-virtual { p3, p1 }, Lorg/mozilla/javascript/xml/XMLObject;->getExtraMethodSource(Lorg/mozilla/javascript/Context;)Lorg/mozilla/javascript/Scriptable;
    move-result-object p3
    if-eqz p3, :L2
    instance-of v2, p3, Lorg/mozilla/javascript/xml/XMLObject;
    if-nez v2, :L1
    invoke-static { p3, v0 }, Lorg/mozilla/javascript/ScriptableObject;->getProperty(Lorg/mozilla/javascript/Scriptable;Ljava/lang/String;)Ljava/lang/Object;
    move-result-object v1
    goto :L1
  :L3
    instance-of p3, v1, Lorg/mozilla/javascript/Callable;
    if-eqz p3, :L4
    check-cast v1, Lorg/mozilla/javascript/Callable;
    invoke-interface { v1, p1, p2, v2, p4 }, Lorg/mozilla/javascript/Callable;->call(Lorg/mozilla/javascript/Context;Lorg/mozilla/javascript/Scriptable;Lorg/mozilla/javascript/Scriptable;[Ljava/lang/Object;)Ljava/lang/Object;
    move-result-object p1
    return-object p1
  :L4
    invoke-static { v2, v1, v0 }, Lorg/mozilla/javascript/ScriptRuntime;->notFunctionError(Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/String;)Ljava/lang/RuntimeException;
    move-result-object p1
    throw p1
  :L5
    const-string p1, "msg.incompat.call"
    invoke-static { p1, v0 }, Lorg/mozilla/javascript/ScriptRuntime;->typeError1(Ljava/lang/String;Ljava/lang/Object;)Lorg/mozilla/javascript/EcmaError;
    move-result-object p1
    throw p1
  :L6
    move-object v2, p0
    move-object v4, p1
    move-object v5, p2
    move-object v6, p3
    move-object v7, p4
    invoke-direct/range { v2 .. v7 }, Lorg/mozilla/javascript/xmlimpl/XMLList;->applyOrCall(ZLorg/mozilla/javascript/Context;Lorg/mozilla/javascript/Scriptable;Lorg/mozilla/javascript/Scriptable;[Ljava/lang/Object;)Ljava/lang/Object;
    move-result-object p1
    return-object p1
  :L7
    invoke-static { p0 }, Lorg/mozilla/javascript/ScriptRuntime;->notFunctionError(Ljava/lang/Object;)Ljava/lang/RuntimeException;
    move-result-object p1
    throw p1
.end method

**Comment by TheRoadX** [comment]
Nightly build for dex2jar 20180327402
![image](https://user-images.githubusercontent.com/12956945/62680086-f9711600-b9e8-11e9-825b-c79bd83abc53.png)

i am use the version , and report NullPointException

at com.googlecode.dex2jar.ir.ts.an.SimpleLiveAnalyze.onUseLocal(SimpleLiveAnalyze.java:89)
	at com.googlecode.dex2jar.ir.ts.an.SimpleLiveAnalyze.onUseLocal(SimpleLiveAnalyze.java:27)
	at com.googlecode.dex2jar.ir.ts.an.BaseAnalyze.onUse(BaseAnalyze.java:166)
	at com.googlecode.dex2jar.ir.ts.an.BaseAnalyze.onUse(BaseAnalyze.java:31)
	at com.googlecode.dex2jar.ir.ts.Cfg.travel(Cfg.java:331)
	at com.googlecode.dex2jar.ir.ts.Cfg.travel(Cfg.java:387)
	at com.googlecode.dex2jar.ir.ts.an.BaseAnalyze.exec(BaseAnalyze.java:90)
