### ISSUE TITLE
A OOM issues

### ISSUE THREAD

**Issue by liu149339750** [pxb1988/dex2jar#278]
C:\Users\deanliu\Desktop\dex-tools-2.1-SNAPSHOT>d2j-dex2jar.bat weixin_1360.apk
dex2jar weixin_1360.apk -> .\weixin_1360-dex2jar.jar
Exception in thread "main" java.lang.OutOfMemoryError: Java heap space
        at com.googlecode.d2j.reader.DexFileReader.getString(DexFileReader.java:964)
        at com.googlecode.d2j.reader.DexFileReader.getType(DexFileReader.java:975)
        at com.googlecode.d2j.reader.DexFileReader.getField(DexFileReader.java:917)
        at com.googlecode.d2j.reader.DexFileReader.acceptInsn(DexFileReader.java:1595)
        at com.googlecode.d2j.reader.DexFileReader.acceptCode(DexFileReader.java:1407)
        at com.googlecode.d2j.reader.DexFileReader.acceptMethod(DexFileReader.java:1058)
        at com.googlecode.d2j.reader.DexFileReader.acceptClass(DexFileReader.java:856)
        at com.googlecode.d2j.reader.DexFileReader.accept(DexFileReader.java:659)
        at com.googlecode.d2j.reader.MultiDexFileReader.accept(MultiDexFileReader.java:116)
        at com.googlecode.d2j.reader.MultiDexFileReader.accept(MultiDexFileReader.java:109)
        at com.googlecode.d2j.dex.Dex2jar.doTranslate(Dex2jar.java:88)
        at com.googlecode.d2j.dex.Dex2jar.to(Dex2jar.java:275)
        at com.googlecode.dex2jar.tools.Dex2jarCmd.doCommandLine(Dex2jarCmd.java:112)
        at com.googlecode.dex2jar.tools.BaseCmd.doMain(BaseCmd.java:290)
        at com.googlecode.dex2jar.tools.Dex2jarCmd.main(Dex2jarCmd.java:33)

**Comment by liu149339750** [comment]
I use dex-tools-2.1-SNAPSHOT

**Comment by Gunkkk** [comment]
have solved?
