### ISSUE TITLE
Can not run on Android devices because the FileSystemProvider don't support jar file

### ISSUE THREAD

**Issue by pansong291** [pxb1988/dex2jar#281]
I wish this program can run on Android devices. But it throws a Exception and tell me `cant find zipfs support`. Please support Android devices.

**Comment by pansong291** [comment]
```
java.io.IOException: cant find zipfs support
	at com.googlecode.d2j.dex.Dex2jar.createZip(Dex2jar.java:294)
	at com.googlecode.d2j.dex.Dex2jar.to(Dex2jar.java:274)
	at com.googlecode.dex2jar.tools.Dex2jarCmd.doCommandLine(Dex2jarCmd.java:107)
	at com.googlecode.dex2jar.tools.BaseCmd.doMain(BaseCmd.java:290)
	at com.googlecode.dex2jar.tools.Dex2jarCmd.main(Dex2jarCmd.java:33)
```
