### ISSUE TITLE
not support dex039: com.googlecode.d2j.DexException: not support version

### ISSUE THREAD

**Issue by lxzh** [pxb1988/dex2jar#319]
```
com.googlecode.d2j.DexException: not support version.
        at com.googlecode.d2j.reader.DexFileReader.<init>(DexFileReader.java:151)
        at com.googlecode.d2j.reader.DexFileReader.<init>(DexFileReader.java:211)
        at com.googlecode.d2j.smali.Baksmali.from(Baksmali.java:33)
        at com.googlecode.d2j.smali.Baksmali.from(Baksmali.java:45)
        at com.googlecode.d2j.smali.BaksmaliCmd.doCommandLine(BaksmaliCmd.java:49)
        at com.googlecode.dex2jar.tools.BaseCmd.doMain(BaseCmd.java:288)
        at com.googlecode.d2j.smali.BaksmaliCmd.main(BaksmaliCmd.java:24)
```
not support `dex039`

**Comment by Niek-Okido** [comment]
get same issue

**Comment by sg552** [comment]
me the same problem. +1 

how to resolve this?

**Comment by sg552** [comment]
OK, I opened the target dex file, and found its header is "dex.039", 
and I found the "dex.035" is good to decompile. 

So I changed 039 to 035, and dex2jar is successful!  ( some succeeded, some still failed ) 

I tried: 
- 039, 038, 037 is not supported
- 036, 035 is good.

**Comment by sg552** [comment]
OK, I download a patched version of dex2jar from here:  https://github.com/DexPatcher/dex2jar/releases

This version can process dex.039.  ( Although sometimes it got error). below is a full list of the dex file I tested: 

```
    size month  datetime filename             status, dexversion and comment
    1328 March  17 09:15 0x74a96c6c30.dex     OK, dex39  android.ext.shared;
   28160 March  17 09:15 0x74a97996dc.dex     Error, dex38: java.lang.IndexOutOfBoundsException     java.nio.Buffer.checkIndex
   15948 March  17 09:15 0x74a9831ff0.dex     Error, dex39: java.lang.ArrayIndexOutOfBoundsException: 0,  at org.objectweb.asm.Type.getType(Type.java:448)
 6991268 March  17 09:15 0x7529208000.dex     OK  , dex35,  com.vip.lueluelue,  okhttp3 third party libs
 6588576 March  17 09:15 0x75298ba000.dex     OK  , dex35,  tencent, mob third party libs
   45616 March  17 09:15 0x752b9b8030.dex	    ok ,  dex35,   qihoo
   45616 March  17 09:15 0x752da01540.dex     ok ,  dex35,   qihoo
     284 March  17 09:15 0x752e50fa8e.dex     ok ,  dex35,   empty class
 7019764 March  17 09:15 0x757dfe6ce0.dex     Error, dex35,   java.lang.IndexOutOfBoundsException 	at java.nio.Buffer.checkIndex(Buffer.java:551)
    1756 March  17 09:15 0x758a600010.dex	    ok,  dex39,   chromiumthird party libs
  431528 March  17 09:15 0x758e83c02c.dex     ok,  dex39,   android.net.ssl, conscrptthird party libs
 1209508 March  17 09:15 0x7595cf10b8.dex     ok,  dex39,   apachethird party libs
 1398708 March  17 09:15 0x7595e1902c.dex	    ok,  dex39,   bouncycastlethird party libs
 3298760 March  17 09:15 0x7595f6f4b4.dex	    ok,  dex39,   android, java, javax, libcorethird party libs
 4946956 March  17 09:15 0x7596295554.dex	    ok,  dex39,   java, javax, sun, jdk.netthird party libs
   60668 March  17 09:15 0x761acfd02c.dex              ok,  dex39,   android.media third party libs
  409152 March  17 09:15 0x761c04302c.dex	    ok,  dex39,   okhttp third party libs

```
