### ISSUE TITLE
d2j-dex2jar.sh: ./d2j_invoke.sh: /bin/sh: bad interpreter: Operation not permitted

### ISSUE THREAD

**Issue by acaixuediananao** [pxb1988/dex2jar#329]
I got error "d2j-dex2jar.sh: ./d2j_invoke.sh: /bin/sh: bad interpreter: Operation not permitted", when i executed the command "sh d2j-dex2jar.sh classes2.dex".
My dex2jar's version is 2.0,i downloaded it from "https://sourceforge.net/projects/dex2jar/files/".
how can solve that problem?

**Comment by acaixuediananao** [comment]
> I got error "d2j-dex2jar.sh: ./d2j_invoke.sh: /bin/sh: bad interpreter: Operation not permitted", when i executed the command "sh d2j-dex2jar.sh classes2.dex".
> My dex2jar's version is 2.0,i downloaded it from "https://sourceforge.net/projects/dex2jar/files/".
> how can solve that problem?

And when i change the version to 0.0.9.15 , the problem is gone .
But there is an another problem, here is the log:

> ➜  dex2jar-0.0.9.15 sh d2j-dex2jar.sh classes.dex
dex2jar classes.dex -> classes-dex2jar.jar
com.googlecode.dex2jar.DexException: while accept method:[Landroid/support/graphics/drawable/AnimatorInflaterCompat;.loadAnimator(Landroid/content/Context;I)Landroid/animation/Animator;]
	at com.googlecode.dex2jar.reader.DexFileReader.acceptMethod(DexFileReader.java:694)
	at com.googlecode.dex2jar.reader.DexFileReader.acceptClass(DexFileReader.java:436)
	at com.googlecode.dex2jar.reader.DexFileReader.accept(DexFileReader.java:323)
	at com.googlecode.dex2jar.v3.Dex2jar.doTranslate(Dex2jar.java:85)
	at com.googlecode.dex2jar.v3.Dex2jar.to(Dex2jar.java:261)
	at com.googlecode.dex2jar.v3.Dex2jar.to(Dex2jar.java:252)
	at com.googlecode.dex2jar.tools.Dex2jarCmd.doCommandLine(Dex2jarCmd.java:110)
	at com.googlecode.dex2jar.tools.BaseCmd.doMain(BaseCmd.java:174)
	at com.googlecode.dex2jar.tools.Dex2jarCmd.main(Dex2jarCmd.java:34)
Caused by: com.googlecode.dex2jar.DexException: while accept parameter annotation in method:[Landroid/support/graphics/drawable/AnimatorInflaterCompat;.loadAnimator(Landroid/content/Context;I)Landroid/animation/Animator;], parameter:[0]
	at com.googlecode.dex2jar.reader.DexFileReader.acceptMethod(DexFileReader.java:663)
	... 8 more
Caused by: java.lang.ArrayIndexOutOfBoundsException: -2034718863
	at java.io.ByteArrayInputStream.read(ByteArrayInputStream.java:144)
	at com.googlecode.dex2jar.reader.io.ArrayDataIn.readUByte(ArrayDataIn.java:133)
	at com.googlecode.dex2jar.reader.DexAnnotationReader.accept(DexAnnotationReader.java:49)
	at com.googlecode.dex2jar.reader.DexFileReader.acceptMethod(DexFileReader.java:660)

**Comment by mowhammadrezaa** [comment]
just do:
chmod +x filename
for any file listed, to allow them to be executed.

**Comment by pxb1988** [comment]
yes, `chmod a+x *.sh` should do the work
