### ISSUE TITLE
dex2jar error report

### ISSUE THREAD

**Issue by mscgo** [pxb1988/dex2jar#331]
Please take a look below

#This file is generated by dex2jar
Please report this file to one of following link if possible (any one).
    https://sourceforge.net/p/dex2jar/tickets/
    https://bitbucket.org/pxb1988/dex2jar/issues
    https://github.com/pxb1988/dex2jar/issues
    dex2jar@googlegroups.com

There are 1 methods fail to translate.
2019-12-23 05:12:57 UTC
version: [dex-reader-2.1-SNAPSHOT, dex-reader-api-2.1-SNAPSHOT, dex-ir-2.1-SNAPSHOT, d2j-smali-2.1-SNAPSHOT, d2j-base-cmd-2.1-SNAPSHOT, dex-tools-2.1-SNAPSHOT, dex-translator-2.1-SNAPSHOT]
cmdline: [../toss/classes.dex, ../toss/classes2.dex, ../toss/classes3.dex]
env:
java.specification.version: 13
java.runtime.version: 13.0.1+9
java.class.path: .:./lib/ST4-4.0.8.jar:./lib/antlr-3.5.2.jar:./lib/antlr-runtime-3.5.2.jar:./lib/antlr4-4.5.jar:./lib/antlr4-runtime-4.5.jar:./lib/asm-debug-all-5.0.3.jar:./lib/d2j-base-cmd-2.1-SNAPSHOT.jar:./lib/d2j-jasmin-2.1-SNAPSHOT.jar:./lib/d2j-smali-2.1-SNAPSHOT.jar:./lib/dex-ir-2.1-SNAPSHOT.jar:./lib/dex-reader-2.1-SNAPSHOT.jar:./lib/dex-reader-api-2.1-SNAPSHOT.jar:./lib/dex-tools-2.1-SNAPSHOT.jar:./lib/dex-translator-2.1-SNAPSHOT.jar:./lib/dex-writer-2.1-SNAPSHOT.jar:./lib/dx-23.0.0.jar:./lib/org.abego.treelayout.core-1.0.1.jar
java.vm.vendor: Oracle Corporation
java.runtime.name: Java(TM) SE Runtime Environment
java.vendor.url: https://java.oracle.com/
java.vm.specification.version: 13
java.vm.name: Java HotSpot(TM) 64-Bit Server VM
java.vendor.url.bug: https://bugreport.java.com/bugreport/
java.io.tmpdir: /var/folders/76/_4lvnt0j05s4s103lt7q666mws8kgf/T/
java.version: 13.0.1
java.specification.vendor: Oracle Corporation
java.vm.specification.name: Java Virtual Machine Specification
java.version.date: 2019-10-15
java.home: /Library/Java/JavaVirtualMachines/jdk-13.0.1.jdk/Contents/Home
java.vm.compressedOopsMode: Zero based
java.library.path: /Users/a/Library/Java/Extensions:/Library/Java/Extensions:/Network/Library/Java/Extensions:/System/Library/Java/Extensions:/usr/lib/java:.
java.vm.specification.vendor: Oracle Corporation
java.specification.name: Java Platform API Specification
java.vm.info: mixed mode, sharing
java.vendor: Oracle Corporation
java.vm.version: 13.0.1+9
java.class.version: 57.0

================= 0 ===================
Lo/сІ;.ˊ(FFLo/сІ$ǃ;)I
java.lang.RuntimeException: fail exe a35 = a28
	at com.googlecode.dex2jar.ir.ts.an.BaseAnalyze.exec(BaseAnalyze.java:92)
	at com.googlecode.dex2jar.ir.ts.an.BaseAnalyze.exec(BaseAnalyze.java:31)
	at com.googlecode.dex2jar.ir.ts.Cfg.dfs(Cfg.java:255)
	at com.googlecode.dex2jar.ir.ts.an.BaseAnalyze.analyze0(BaseAnalyze.java:75)
	at com.googlecode.dex2jar.ir.ts.an.BaseAnalyze.analyze(BaseAnalyze.java:69)
	at com.googlecode.dex2jar.ir.ts.Ir2JRegAssignTransformer.transform(Ir2JRegAssignTransformer.java:182)
	at com.googlecode.d2j.dex.Dex2jar$2.optimize(Dex2jar.java:167)
	at com.googlecode.d2j.dex.Dex2Asm.convertCode(Dex2Asm.java:442)
	at com.googlecode.d2j.dex.ExDex2Asm.convertCode(ExDex2Asm.java:40)
	at com.googlecode.d2j.dex.Dex2jar$2.convertCode(Dex2jar.java:132)
	at com.googlecode.d2j.dex.Dex2Asm.convertMethod(Dex2Asm.java:575)
	at com.googlecode.d2j.dex.Dex2Asm.convertClass(Dex2Asm.java:434)
	at com.googlecode.d2j.dex.Dex2Asm.convertDex(Dex2Asm.java:450)
	at com.googlecode.d2j.dex.Dex2jar.doTranslate(Dex2jar.java:175)
	at com.googlecode.d2j.dex.Dex2jar.to(Dex2jar.java:275)
	at com.googlecode.dex2jar.tools.Dex2jarCmd.doCommandLine(Dex2jarCmd.java:112)
	at com.googlecode.dex2jar.tools.BaseCmd.doMain(BaseCmd.java:290)
	at com.googlecode.dex2jar.tools.Dex2jarCmd.main(Dex2jarCmd.java:33)
Caused by: java.lang.NullPointerException
	at com.googlecode.dex2jar.ir.ts.an.SimpleLiveAnalyze.onUseLocal(SimpleLiveAnalyze.java:89)
	at com.googlecode.dex2jar.ir.ts.an.SimpleLiveAnalyze.onUseLocal(SimpleLiveAnalyze.java:27)
	at com.googlecode.dex2jar.ir.ts.an.BaseAnalyze.onUse(BaseAnalyze.java:166)
	at com.googlecode.dex2jar.ir.ts.an.BaseAnalyze.onUse(BaseAnalyze.java:31)
	at com.googlecode.dex2jar.ir.ts.Cfg.travel(Cfg.java:331)
	at com.googlecode.dex2jar.ir.ts.Cfg.travel(Cfg.java:387)
	at com.googlecode.dex2jar.ir.ts.an.BaseAnalyze.exec(BaseAnalyze.java:90)
	... 17 more

.method private \u02ca(FFLo/\u0441\u0406$\u01c3;)I
  .registers 14
    iget-object v0, p0, Lo/\u0441\u0406;->ˎ:Ljava/util/List;
    const/4 v1, -1
    if-eqz v0, :L16
    invoke-interface { v0 }, Ljava/util/List;->isEmpty()Z
    move-result v0
    if-eqz v0, :L0
    goto/16 :L16
  :L0
    const/4 v0, 0
    iget-object v2, p0, Lo/\u0441\u0406;->ˎ:Ljava/util/List;
    invoke-interface { v2 }, Ljava/util/List;->size()I
    move-result v2
    add-int/lit8 v2, v2, -1
  :L1
    if-ge v0, v2, :L7
    add-int v3, v0, v2
    div-int/lit8 v3, v3, 2
    iget-object v4, p0, Lo/\u0441\u0406;->ˎ:Ljava/util/List;
    invoke-interface { v4, v3 }, Ljava/util/List;->get(I)Ljava/lang/Object;
    move-result-object v4
    check-cast v4, Lo/\u0441\u0399;
    invoke-virtual { v4 }, Lo/\u0441\u0399;->\u02cb()F
    move-result v4
    sub-float/2addr v4, p1
    iget-object v5, p0, Lo/\u0441\u0406;->ˎ:Ljava/util/List;
    add-int/lit8 v6, v3, 1
    invoke-interface { v5, v6 }, Ljava/util/List;->get(I)Ljava/lang/Object;
    move-result-object v5
    check-cast v5, Lo/\u0441\u0399;
    invoke-virtual { v5 }, Lo/\u0441\u0399;->\u02cb()F
    move-result v5
    sub-float/2addr v5, p1
    invoke-static { v4 }, Ljava/lang/Math;->abs(F)F
    move-result v7
    invoke-static { v5 }, Ljava/lang/Math;->abs(F)F
    move-result v5
    cmpg-float v8, v5, v7
    if-gez v8, :L3
  :L2
    move v0, v6
    goto :L1
  :L3
    cmpg-float v5, v7, v5
    if-gez v5, :L4
    goto :L5
  :L4
    float-to-double v4, v4
    const-wide/16 v7, 0
    cmpl-double v9, v4, v7
    if-ltz v9, :L6
  :L5
    move v2, v3
    goto :L1
  :L6
    cmpg-double v3, v4, v7
    if-gez v3, :L1
    goto :L2
  :L7
    if-eq v2, v1, :L15
    iget-object v0, p0, Lo/\u0441\u0406;->ˎ:Ljava/util/List;
    invoke-interface { v0, v2 }, Ljava/util/List;->get(I)Ljava/lang/Object;
    move-result-object v0
    check-cast v0, Lo/\u0441\u0399;
    invoke-virtual { v0 }, Lo/\u0441\u0399;->\u02cb()F
    move-result v0
    sget-object v1, Lo/\u0441\u0406$\u01c3;->UP:Lo/\u0441\u0406$\u01c3;
    if-ne p3, v1, :L8
    cmpg-float p1, v0, p1
    if-gez p1, :L9
    iget-object p1, p0, Lo/\u0441\u0406;->ˎ:Ljava/util/List;
    invoke-interface { p1 }, Ljava/util/List;->size()I
    move-result p1
    add-int/lit8 p1, p1, -1
    if-ge v2, p1, :L9
    add-int/lit8 v2, v2, 1
    goto :L9
  :L8
    sget-object v1, Lo/\u0441\u0406$\u01c3;->DOWN:Lo/\u0441\u0406$\u01c3;
    if-ne p3, v1, :L9
    cmpl-float p1, v0, p1
    if-lez p1, :L9
    if-lez v2, :L9
    add-int/lit8 v2, v2, -1
  :L9
    invoke-static { p2 }, Ljava/lang/Float;->isNaN(F)Z
    move-result p1
    if-nez p1, :L15
  :L10
    if-lez v2, :L11
    iget-object p1, p0, Lo/\u0441\u0406;->ˎ:Ljava/util/List;
    add-int/lit8 p3, v2, -1
    invoke-interface { p1, p3 }, Ljava/util/List;->get(I)Ljava/lang/Object;
    move-result-object p1
    check-cast p1, Lo/\u0441\u0399;
    invoke-virtual { p1 }, Lo/\u0441\u0399;->\u02cb()F
    move-result p1
    cmpl-float p1, p1, v0
    if-nez p1, :L11
    add-int/lit8 v2, v2, -1
    goto :L10
  :L11
    iget-object p1, p0, Lo/\u0441\u0406;->ˎ:Ljava/util/List;
    invoke-interface { p1, v2 }, Ljava/util/List;->get(I)Ljava/lang/Object;
    move-result-object p1
    check-cast p1, Lo/\u0441\u0399;
    iget p1, p1, Lo/\u0417;->ˎ:F
    move p3, p1
  :L12
    move p1, v2
  :L13
    add-int/lit8 v2, v2, 1
    iget-object v1, p0, Lo/\u0441\u0406;->ˎ:Ljava/util/List;
    invoke-interface { v1 }, Ljava/util/List;->size()I
    move-result v1
    if-ge v2, v1, :L14
    iget-object v1, p0, Lo/\u0441\u0406;->ˎ:Ljava/util/List;
    invoke-interface { v1, v2 }, Ljava/util/List;->get(I)Ljava/lang/Object;
    move-result-object v1
    check-cast v1, Lo/\u0441\u0399;
    invoke-virtual { v1 }, Lo/\u0441\u0399;->\u02cb()F
    move-result v3
    cmpl-float v3, v3, v0
    if-nez v3, :L14
    iget v1, v1, Lo/\u0417;->ˎ:F
    sub-float/2addr v1, p2
    invoke-static { v1 }, Ljava/lang/Math;->abs(F)F
    move-result v1
    sub-float v3, p3, p2
    invoke-static { v3 }, Ljava/lang/Math;->abs(F)F
    move-result v3
    cmpg-float v1, v1, v3
    if-gez v1, :L13
    move p3, p2
    goto :L12
  :L14
    move v2, p1
  :L15
    return v2
  :L16
    return v1
.end method

**Comment by sulaymanyf** [comment]
#This file is generated by dex2jar
Please report this file to one of following link if possible (any one).
    https://sourceforge.net/p/dex2jar/tickets/
    https://bitbucket.org/pxb1988/dex2jar/issues
    https://github.com/pxb1988/dex2jar/issues
    dex2jar@googlegroups.com

There are 1 methods fail to translate.
2020-05-12 03:01:16 UTC
version: [dex-reader-2.1-SNAPSHOT, dex-reader-api-2.1-SNAPSHOT, dex-ir-2.1-SNAPSHOT, d2j-smali-2.1-SNAPSHOT, d2j-base-cmd-2.1-SNAPSHOT, dex-tools-2.1-SNAPSHOT, dex-translator-2.1-SNAPSHOT]
cmdline: [D:\apk\sahibinden\classes.dex]
env:
java.runtime.name: Java(TM) SE Runtime Environment
java.vm.version: 25.131-b11
java.vm.vendor: Oracle Corporation
java.vendor.url: http://java.oracle.com/
java.vm.name: Java HotSpot(TM) 64-Bit Server VM
java.vm.specification.name: Java Virtual Machine Specification
java.runtime.version: 1.8.0_131-b11
java.awt.graphicsenv: sun.awt.Win32GraphicsEnvironment
java.endorsed.dirs: D:\java\devsoft\jre\jre8\lib\endorsed
java.io.tmpdir: C:\Users\SULAYM~1\AppData\Local\Temp\
java.vm.specification.vendor: Oracle Corporation
java.library.path: C:\Program Files (x86)\Common Files\Oracle\Java\javapath;C:\WINDOWS\Sun\Java\bin;C:\WINDOWS\system32;C:\WINDOWS;C:\Program Files (x86)\Common Files\Oracle\Java\javapath;D:\Program Files\Python37\Scripts\;D:\Program Files\Python37\;C:\ProgramData\Oracle\Java\javapath;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\OpenSSH\;D:\java\devsoft\jdk\java8\bin;d:\Program Files\Git\cmd;D:\Program Files\TortoiseGit\bin;D:\Program Files\mysql-8.0.16-winx64\\bin;D:\gradle\gradle-5.4.1\bin;D:\java\devsoft\apache-maven-3.6.0\bin;D:\java\devsoft\jdk\java8\\bin;D:\Program Files\PuTTY\;D:\flutter\bin;D:\Program Files\nodejs\;C:\Users\sulaymanyf\AppData\Local\Yarn\\bin;C:\Users\sulaymanyf\AppData\Local\Programs\Python\Python36;C:\Program Files\LibreOffice\program;C:\Program Files\dotnet\;C:\Program Files\Dart\dart-sdk\bin;D:\dart\flutter\bin;D:\godev\bin;D:\Program Files\Tesseract-OCR;d:\python\project\ai_asistan\venv\lib\site-packages;D:\python\devSoft;C:\Program Files\Redis\;D:\Go\bin;C:\Programs\Python\Python36\Scripts\;C:\Programs\Python\Python36\;d:\Ruby25-x64\bin;C:\Users\sulaymanyf\AppData\Local\Microsoft\WindowsApps;;d:\Program Files\JetBrains\IntelliJ IDEA 2019.1.3\bin;;d:\Program Files\JetBrains\RubyMine 2019.1.2\bin;;d:\Program Files\JetBrains\PyCharm 2019.1.3\bin;;C:\Users\sulaymanyf\AppData\Local\Programs\Microsoft VS Code\bin;d:\Programs\Fiddler;C:\Users\sulaymanyf\AppData\Roaming\npm;C:\Users\sulaymanyf\AppData\Roaming\npm;D:\Program Files\MicrosoftVSCode\Microsoft VS Code\bin;C:\Users\sulaymanyf\.dotnet\tools;.
java.specification.name: Java Platform API Specification
java.class.version: 52.0
java.awt.printerjob: sun.awt.windows.WPrinterJob
java.specification.version: 1.8
java.class.path: D:\Users\dex-tools-2.1-SNAPSHOT\lib\antlr-3.5.2.jar;D:\Users\dex-tools-2.1-SNAPSHOT\lib\antlr-runtime-3.5.2.jar;D:\Users\dex-tools-2.1-SNAPSHOT\lib\antlr4-4.5.jar;D:\Users\dex-tools-2.1-SNAPSHOT\lib\antlr4-runtime-4.5.jar;D:\Users\dex-tools-2.1-SNAPSHOT\lib\asm-debug-all-5.0.3.jar;D:\Users\dex-tools-2.1-SNAPSHOT\lib\d2j-base-cmd-2.1-SNAPSHOT.jar;D:\Users\dex-tools-2.1-SNAPSHOT\lib\d2j-jasmin-2.1-SNAPSHOT.jar;D:\Users\dex-tools-2.1-SNAPSHOT\lib\d2j-smali-2.1-SNAPSHOT.jar;D:\Users\dex-tools-2.1-SNAPSHOT\lib\dex-ir-2.1-SNAPSHOT.jar;D:\Users\dex-tools-2.1-SNAPSHOT\lib\dex-reader-2.1-SNAPSHOT.jar;D:\Users\dex-tools-2.1-SNAPSHOT\lib\dex-reader-api-2.1-SNAPSHOT.jar;D:\Users\dex-tools-2.1-SNAPSHOT\lib\dex-tools-2.1-SNAPSHOT.jar;D:\Users\dex-tools-2.1-SNAPSHOT\lib\dex-translator-2.1-SNAPSHOT.jar;D:\Users\dex-tools-2.1-SNAPSHOT\lib\dex-writer-2.1-SNAPSHOT.jar;D:\Users\dex-tools-2.1-SNAPSHOT\lib\dx-23.0.0.jar;D:\Users\dex-tools-2.1-SNAPSHOT\lib\org.abego.treelayout.core-1.0.1.jar;D:\Users\dex-tools-2.1-SNAPSHOT\lib\ST4-4.0.8.jar;
java.vm.specification.version: 1.8
java.home: D:\java\devsoft\jre\jre8
java.specification.vendor: Oracle Corporation
java.vm.info: mixed mode
java.version: 1.8.0_131
java.ext.dirs: D:\java\devsoft\jre\jre8\lib\ext;C:\WINDOWS\Sun\Java\lib\ext
java.vendor: Oracle Corporation
java.vendor.url.bug: http://bugreport.sun.com/bugreport/

================= 0 ===================
Lcom/github/mikephil/charting/data/DataSet;.b(FFLcom/github/mikephil/charting/data/DataSet$Rounding;)I
java.lang.RuntimeException: fail exe a35 = a28
	at com.googlecode.dex2jar.ir.ts.an.BaseAnalyze.exec(BaseAnalyze.java:92)
	at com.googlecode.dex2jar.ir.ts.an.BaseAnalyze.exec(BaseAnalyze.java:31)
	at com.googlecode.dex2jar.ir.ts.Cfg.dfs(Cfg.java:255)
	at com.googlecode.dex2jar.ir.ts.an.BaseAnalyze.analyze0(BaseAnalyze.java:75)
	at com.googlecode.dex2jar.ir.ts.an.BaseAnalyze.analyze(BaseAnalyze.java:69)
	at com.googlecode.dex2jar.ir.ts.Ir2JRegAssignTransformer.transform(Ir2JRegAssignTransformer.java:182)
	at com.googlecode.d2j.dex.Dex2jar$2.optimize(Dex2jar.java:167)
	at com.googlecode.d2j.dex.Dex2Asm.convertCode(Dex2Asm.java:442)
	at com.googlecode.d2j.dex.ExDex2Asm.convertCode(ExDex2Asm.java:40)
	at com.googlecode.d2j.dex.Dex2jar$2.convertCode(Dex2jar.java:132)
	at com.googlecode.d2j.dex.Dex2Asm.convertMethod(Dex2Asm.java:575)
	at com.googlecode.d2j.dex.Dex2Asm.convertClass(Dex2Asm.java:434)
	at com.googlecode.d2j.dex.Dex2Asm.convertDex(Dex2Asm.java:450)
	at com.googlecode.d2j.dex.Dex2jar.doTranslate(Dex2jar.java:175)
	at com.googlecode.d2j.dex.Dex2jar.to(Dex2jar.java:275)
	at com.googlecode.dex2jar.tools.Dex2jarCmd.doCommandLine(Dex2jarCmd.java:112)
	at com.googlecode.dex2jar.tools.BaseCmd.doMain(BaseCmd.java:290)
	at com.googlecode.dex2jar.tools.Dex2jarCmd.main(Dex2jarCmd.java:33)
Caused by: java.lang.NullPointerException
	at com.googlecode.dex2jar.ir.ts.an.SimpleLiveAnalyze.onUseLocal(SimpleLiveAnalyze.java:89)
	at com.googlecode.dex2jar.ir.ts.an.SimpleLiveAnalyze.onUseLocal(SimpleLiveAnalyze.java:27)
	at com.googlecode.dex2jar.ir.ts.an.BaseAnalyze.onUse(BaseAnalyze.java:166)
	at com.googlecode.dex2jar.ir.ts.an.BaseAnalyze.onUse(BaseAnalyze.java:31)
	at com.googlecode.dex2jar.ir.ts.Cfg.travel(Cfg.java:331)
	at com.googlecode.dex2jar.ir.ts.Cfg.travel(Cfg.java:387)
	at com.googlecode.dex2jar.ir.ts.an.BaseAnalyze.exec(BaseAnalyze.java:90)
	... 17 more


.method public b(FFLcom/github/mikephil/charting/data/DataSet$Rounding;)I
  .registers 14
    iget-object v0, p0, Lcom/github/mikephil/charting/data/DataSet;->q:Ljava/util/List;
    const/4 v1, -1
    if-eqz v0, :L18
    invoke-interface { v0 }, Ljava/util/List;->isEmpty()Z
    move-result v0
    if-eqz v0, :L0
    goto/16 :L18
  :L0
    const/4 v0, 0
    iget-object v2, p0, Lcom/github/mikephil/charting/data/DataSet;->q:Ljava/util/List;
    invoke-interface { v2 }, Ljava/util/List;->size()I
    move-result v2
    add-int/lit8 v2, v2, -1
  :L1
    if-ge v0, v2, :L7
    add-int v3, v0, v2
    div-int/lit8 v3, v3, 2
    iget-object v4, p0, Lcom/github/mikephil/charting/data/DataSet;->q:Ljava/util/List;
    invoke-interface { v4, v3 }, Ljava/util/List;->get(I)Ljava/lang/Object;
    move-result-object v4
    check-cast v4, Lcom/github/mikephil/charting/data/Entry;
    invoke-virtual { v4 }, Lcom/github/mikephil/charting/data/Entry;->f()F
    move-result v4
    sub-float/2addr v4, p1
    iget-object v5, p0, Lcom/github/mikephil/charting/data/DataSet;->q:Ljava/util/List;
    add-int/lit8 v6, v3, 1
    invoke-interface { v5, v6 }, Ljava/util/List;->get(I)Ljava/lang/Object;
    move-result-object v5
    check-cast v5, Lcom/github/mikephil/charting/data/Entry;
    invoke-virtual { v5 }, Lcom/github/mikephil/charting/data/Entry;->f()F
    move-result v5
    sub-float/2addr v5, p1
    invoke-static { v4 }, Ljava/lang/Math;->abs(F)F
    move-result v7
    invoke-static { v5 }, Ljava/lang/Math;->abs(F)F
    move-result v5
    cmpg-float v8, v5, v7
    if-gez v8, :L3
  :L2
    move v0, v6
    goto :L1
  :L3
    cmpg-float v5, v7, v5
    if-gez v5, :L4
    goto :L5
  :L4
    float-to-double v4, v4
    const-wide/16 v7, 0
    cmpl-double v9, v4, v7
    if-ltz v9, :L6
  :L5
    move v2, v3
    goto :L1
  :L6
    cmpg-double v3, v4, v7
    if-gez v3, :L1
    goto :L2
  :L7
    if-eq v2, v1, :L17
    iget-object v0, p0, Lcom/github/mikephil/charting/data/DataSet;->q:Ljava/util/List;
    invoke-interface { v0, v2 }, Ljava/util/List;->get(I)Ljava/lang/Object;
    move-result-object v0
    check-cast v0, Lcom/github/mikephil/charting/data/Entry;
    invoke-virtual { v0 }, Lcom/github/mikephil/charting/data/Entry;->f()F
    move-result v0
    sget-object v1, Lcom/github/mikephil/charting/data/DataSet$Rounding;->UP:Lcom/github/mikephil/charting/data/DataSet$Rounding;
    if-ne p3, v1, :L8
    cmpg-float p1, v0, p1
    if-gez p1, :L9
    iget-object p1, p0, Lcom/github/mikephil/charting/data/DataSet;->q:Ljava/util/List;
    invoke-interface { p1 }, Ljava/util/List;->size()I
    move-result p1
    add-int/lit8 p1, p1, -1
    if-ge v2, p1, :L9
    add-int/lit8 v2, v2, 1
    goto :L9
  :L8
    sget-object v1, Lcom/github/mikephil/charting/data/DataSet$Rounding;->DOWN:Lcom/github/mikephil/charting/data/DataSet$Rounding;
    if-ne p3, v1, :L9
    cmpl-float p1, v0, p1
    if-lez p1, :L9
    if-lez v2, :L9
    add-int/lit8 v2, v2, -1
  :L9
    invoke-static { p2 }, Ljava/lang/Float;->isNaN(F)Z
    move-result p1
    if-nez p1, :L17
  :L10
    if-lez v2, :L11
    iget-object p1, p0, Lcom/github/mikephil/charting/data/DataSet;->q:Ljava/util/List;
    add-int/lit8 p3, v2, -1
    invoke-interface { p1, p3 }, Ljava/util/List;->get(I)Ljava/lang/Object;
    move-result-object p1
    check-cast p1, Lcom/github/mikephil/charting/data/Entry;
    invoke-virtual { p1 }, Lcom/github/mikephil/charting/data/Entry;->f()F
    move-result p1
    cmpl-float p1, p1, v0
    if-nez p1, :L11
    add-int/lit8 v2, v2, -1
    goto :L10
  :L11
    iget-object p1, p0, Lcom/github/mikephil/charting/data/DataSet;->q:Ljava/util/List;
    invoke-interface { p1, v2 }, Ljava/util/List;->get(I)Ljava/lang/Object;
    move-result-object p1
    check-cast p1, Lcom/github/mikephil/charting/data/Entry;
    invoke-virtual { p1 }, Lf1;->e()F
    move-result p1
  :L12
    move p3, v2
  :L13
    add-int/lit8 v2, v2, 1
    iget-object v1, p0, Lcom/github/mikephil/charting/data/DataSet;->q:Ljava/util/List;
    invoke-interface { v1 }, Ljava/util/List;->size()I
    move-result v1
    if-lt v2, v1, :L14
    goto :L15
  :L14
    iget-object v1, p0, Lcom/github/mikephil/charting/data/DataSet;->q:Ljava/util/List;
    invoke-interface { v1, v2 }, Ljava/util/List;->get(I)Ljava/lang/Object;
    move-result-object v1
    check-cast v1, Lcom/github/mikephil/charting/data/Entry;
    invoke-virtual { v1 }, Lcom/github/mikephil/charting/data/Entry;->f()F
    move-result v3
    cmpl-float v3, v3, v0
    if-eqz v3, :L16
  :L15
    move v2, p3
    goto :L17
  :L16
    invoke-virtual { v1 }, Lf1;->e()F
    move-result v1
    sub-float/2addr v1, p2
    invoke-static { v1 }, Ljava/lang/Math;->abs(F)F
    move-result v1
    sub-float v3, p1, p2
    invoke-static { v3 }, Ljava/lang/Math;->abs(F)F
    move-result v3
    cmpg-float v1, v1, v3
    if-gez v1, :L13
    move p1, p2
    goto :L12
  :L17
    return v2
  :L18
    return v1
.end method
