### ISSUE TITLE
report this file to one of following link if possible

### ISSUE THREAD

**Issue by mrmedjbour** [pxb1988/dex2jar#412]
i'm having this problem 
`#This file is generated by dex2jar
Please report this file to one of following link if possible (any one).
    https://sourceforge.net/p/dex2jar/tickets/
    https://bitbucket.org/pxb1988/dex2jar/issues
    https://github.com/pxb1988/dex2jar/issues
    dex2jar@googlegroups.com

There are 1 methods fail to translate.
2020-10-02 13:06:16 UTC
version: [dex-reader-2.1-SNAPSHOT, dex-reader-api-2.1-SNAPSHOT, dex-ir-2.1-SNAPSHOT, d2j-smali-2.1-SNAPSHOT, d2j-base-cmd-2.1-SNAPSHOT, dex-tools-2.1-SNAPSHOT, dex-translator-2.1-SNAPSHOT]
cmdline: [../eMeals_base.apk]
env:
java.specification.version: 11
java.class.path: .:./lib/ST4-4.0.8.jar:./lib/antlr-3.5.2.jar:./lib/antlr-runtime-3.5.2.jar:./lib/antlr4-4.5.jar:./lib/antlr4-runtime-4.5.jar:./lib/asm-debug-all-5.0.3.jar:./lib/d2j-base-cmd-2.1-SNAPSHOT.jar:./lib/d2j-jasmin-2.1-SNAPSHOT.jar:./lib/d2j-smali-2.1-SNAPSHOT.jar:./lib/dex-ir-2.1-SNAPSHOT.jar:./lib/dex-reader-2.1-SNAPSHOT.jar:./lib/dex-reader-api-2.1-SNAPSHOT.jar:./lib/dex-tools-2.1-SNAPSHOT.jar:./lib/dex-translator-2.1-SNAPSHOT.jar:./lib/dex-writer-2.1-SNAPSHOT.jar:./lib/dx-23.0.0.jar:./lib/org.abego.treelayout.core-1.0.1.jar
java.vm.vendor: Debian
java.vendor.url: https://tracker.debian.org/openjdk-11
java.vm.specification.version: 11
java.specification.vendor: Oracle Corporation
java.version.date: 2020-04-14
java.home: /usr/lib/jvm/java-11-openjdk-amd64
java.vm.compressedOopsMode: 32-bit
java.specification.name: Java Platform API Specification
java.vm.specification.vendor: Oracle Corporation
java.awt.graphicsenv: sun.awt.X11GraphicsEnvironment
java.runtime.version: 11.0.7-ea+9-post-Debian-1
java.runtime.name: OpenJDK Runtime Environment
java.vm.name: OpenJDK 64-Bit Server VM
java.vendor.url.bug: https://bugs.debian.org/openjdk-11
java.io.tmpdir: /tmp
java.version: 11.0.7-ea
java.vm.specification.name: Java Virtual Machine Specification
java.awt.printerjob: sun.print.PSPrinterJob
java.library.path: /usr/java/packages/lib:/usr/lib/x86_64-linux-gnu/jni:/lib/x86_64-linux-gnu:/usr/lib/x86_64-linux-gnu:/usr/lib/jni:/lib:/usr/lib
java.vendor: Debian
java.vm.info: mixed mode, sharing
java.vm.version: 11.0.7-ea+9-post-Debian-1
java.class.version: 55.0

================= 0 ===================
Landroidx/core/text/BidiFormatter$DirectionalityEstimator;.getExitDir()I
java.lang.RuntimeException: fail exe a8 = a0
	at com.googlecode.dex2jar.ir.ts.an.BaseAnalyze.exec(BaseAnalyze.java:92)
	at com.googlecode.dex2jar.ir.ts.an.BaseAnalyze.exec(BaseAnalyze.java:31)
	at com.googlecode.dex2jar.ir.ts.Cfg.dfs(Cfg.java:255)
	at com.googlecode.dex2jar.ir.ts.an.BaseAnalyze.analyze0(BaseAnalyze.java:75)
	at com.googlecode.dex2jar.ir.ts.an.BaseAnalyze.analyze(BaseAnalyze.java:69)
	at com.googlecode.dex2jar.ir.ts.Ir2JRegAssignTransformer.transform(Ir2JRegAssignTransformer.java:182)
	at com.googlecode.d2j.dex.Dex2jar$2.optimize(Dex2jar.java:167)
	at com.googlecode.d2j.dex.Dex2Asm.convertCode(Dex2Asm.java:442)
	at com.googlecode.d2j.dex.ExDex2Asm.convertCode(ExDex2Asm.java:40)
	at com.googlecode.d2j.dex.Dex2jar$2.convertCode(Dex2jar.java:132)
	at com.googlecode.d2j.dex.Dex2Asm.convertMethod(Dex2Asm.java:575)
	at com.googlecode.d2j.dex.Dex2Asm.convertClass(Dex2Asm.java:434)
	at com.googlecode.d2j.dex.Dex2Asm.convertDex(Dex2Asm.java:450)
	at com.googlecode.d2j.dex.Dex2jar.doTranslate(Dex2jar.java:175)
	at com.googlecode.d2j.dex.Dex2jar.to(Dex2jar.java:275)
	at com.googlecode.dex2jar.tools.Dex2jarCmd.doCommandLine(Dex2jarCmd.java:112)
	at com.googlecode.dex2jar.tools.BaseCmd.doMain(BaseCmd.java:290)
	at com.googlecode.dex2jar.tools.Dex2jarCmd.main(Dex2jarCmd.java:33)
Caused by: java.lang.NullPointerException
	at com.googlecode.dex2jar.ir.ts.an.SimpleLiveAnalyze.onUseLocal(SimpleLiveAnalyze.java:89)
	at com.googlecode.dex2jar.ir.ts.an.SimpleLiveAnalyze.onUseLocal(SimpleLiveAnalyze.java:27)
	at com.googlecode.dex2jar.ir.ts.an.BaseAnalyze.onUse(BaseAnalyze.java:166)
	at com.googlecode.dex2jar.ir.ts.an.BaseAnalyze.onUse(BaseAnalyze.java:31)
	at com.googlecode.dex2jar.ir.ts.Cfg.travel(Cfg.java:331)
	at com.googlecode.dex2jar.ir.ts.Cfg.travel(Cfg.java:387)
	at com.googlecode.dex2jar.ir.ts.an.BaseAnalyze.exec(BaseAnalyze.java:90)
	... 17 more

.method getExitDir()I
  .registers 8
    iget v0, p0, Landroidx/core/text/BidiFormatter$DirectionalityEstimator;->length:I
    iput v0, p0, Landroidx/core/text/BidiFormatter$DirectionalityEstimator;->charIndex:I
    const/4 v0, 0
    move v1, v0
  :L0
    move v2, v1
  :L1
    iget v3, p0, Landroidx/core/text/BidiFormatter$DirectionalityEstimator;->charIndex:I
    if-lez v3, :L11
    invoke-virtual { p0 }, Landroidx/core/text/BidiFormatter$DirectionalityEstimator;->dirTypeBackward()B
    move-result v3
    const/4 v4, -1
    if-eqz v3, :L8
    const/4 v5, 1
    if-eq v3, v5, :L6
    const/4 v6, 2
    if-eq v3, v6, :L6
    const/16 v6, 9
    if-eq v3, v6, :L1
    packed-switch v3, :L12
    if-nez v2, :L1
    goto :L10
  :L2
    add-int/lit8 v1, v1, 1
    goto :L1
  :L3
    if-ne v2, v1, :L5
    return v5
  :L4
    if-ne v2, v1, :L5
    return v4
  :L5
    add-int/lit8 v1, v1, -1
    goto :L1
  :L6
    if-nez v1, :L7
    return v5
  :L7
    if-nez v2, :L1
    goto :L10
  :L8
    if-nez v1, :L9
    return v4
  :L9
    if-nez v2, :L1
  :L10
    goto :L0
  :L11
    return v0
  :L12
  .packed-switch 14
    :L4
    :L4
    :L3
    :L3
    :L2
  .end packed-switch
.end method`

**Comment by haijingtech** [comment]
Hello,  i got the same problem. Did you fix the problem?
