### ISSUE TITLE
Error report

### ISSUE THREAD

**Issue by magliocchetti** [pxb1988/dex2jar#452]
Apk I was using dex2jar on: https://bit.ly/3cIK0in
Error zip: [ig-error.zip](https://github.com/pxb1988/dex2jar/files/6250977/ig-error.zip)

**Comment by geilige** [comment]
> Apk I was using dex2jar on: https://bit.ly/3cIK0in
> Error zip: [ig-error.zip](https://github.com/pxb1988/dex2jar/files/6250977/ig-error.zip)

试试看 https://github.com/geilige/dex2jar/releases

**Comment by magliocchetti** [comment]
> > Apk I was using dex2jar on: https://bit.ly/3cIK0in
> > Error zip: [ig-error.zip](https://github.com/pxb1988/dex2jar/files/6250977/ig-error.zip)
> 
> 试试看 https://github.com/geilige/dex2jar/releases

I tried but unfortunately still gives me error.
Apk I was using dex2jar on: same as the first post
Error zip: [ig-error.zip](https://github.com/pxb1988/dex2jar/files/6275325/ig-error.zip)

**Comment by nick-botticelli** [comment]
I tried the APK you linked and didn't find any errors using this fork https://github.com/ThexXTURBOXx/dex2jar, so try using that and see if your issue is fixed.

**Comment by pxb1988** [comment]
the dex works on lastest release https://github.com/pxb1988/dex2jar/releases please have a try.

please note, there are some class (`X/0ih`) which has an invalidate class name (`0` is not allow here).

```
Invalid owner (must be a fully qualified class name in internal form): X/0ih
java.lang.IllegalArgumentException: Invalid owner (must be a fully qualified class name in internal form): X/0ih
	at org.objectweb.asm.util.CheckMethodAdapter.checkInternalName(CheckMethodAdapter.java:1351)
	at org.objectweb.asm.util.CheckMethodAdapter.checkInternalName(CheckMethodAdapter.java:1318)
	at org.objectweb.asm.util.CheckMethodAdapter.visitFieldInsn(CheckMethodAdapter.java:680)
	at org.objectweb.asm.ClassReader.readCode(ClassReader.java:1414)
	at org.objectweb.asm.ClassReader.readMethod(ClassReader.java:1017)
	at org.objectweb.asm.ClassReader.accept(ClassReader.java:693)
	at org.objectweb.asm.ClassReader.accept(ClassReader.java:506)
	at com.googlecode.dex2jar.test.TestUtils.verify(TestUtils.java:244)
```
