### ISSUE TITLE
java.lang.StringIndexOutOfBoundsException: begin 1, end -1, length 2

### ISSUE THREAD

**Issue by RussiaVk** [pxb1988/dex2jar#455]
```
 java.lang.StringIndexOutOfBoundsException: begin 1, end -1, length 2
        at java.base/java.lang.String.checkBoundsBeginEnd(String.java:3734)
        at java.base/java.lang.String.substring(String.java:1903)
        at org.objectweb.asm.signature.SignatureReader.parseType(SignatureReader.java:169)
        at org.objectweb.asm.signature.SignatureReader.acceptType(SignatureReader.java:130)
        at org.objectweb.asm.commons.Remapper.mapSignature(Remapper.java:162)
        at org.objectweb.asm.commons.RemappingClassAdapter.visitField(RemappingClassAdapter.java:90)
        at org.objectweb.asm.ClassVisitor.visitField(ClassVisitor.java:272)
        at com.googlecode.d2j.dex.Dex2Asm.convertField(Dex2Asm.java:488)
        at com.googlecode.d2j.dex.Dex2Asm.convertClass(Dex2Asm.java:439)
        at com.googlecode.d2j.dex.Dex2Asm.convertClass(Dex2Asm.java:357)
        at com.googlecode.d2j.dex.Dex2Asm.convertDex(Dex2Asm.java:460)
        at com.googlecode.d2j.dex.Dex2jar.doTranslate(Dex2jar.java:175)
        at com.googlecode.d2j.dex.Dex2jar.to(Dex2jar.java:275)
        at com.googlecode.dex2jar.tools.Dex2jarCmd.doCommandLine(Dex2jarCmd.java:112)
        at com.googlecode.dex2jar.tools.BaseCmd.doMain(BaseCmd.java:290)
        at com.googlecode.dex2jar.tools.Dex2jarCmd.main(Dex2jarCmd.java:33)

[classes.zip](https://github.com/pxb1988/dex2jar/files/6295768/classes.zip)


```

**Comment by GolubevDenis** [comment]
Have the same issue. There are any updates?

**Comment by PratapNaik** [comment]
bump!

**Comment by nick-botticelli** [comment]
It looks like this issue may be fixed on this branch https://github.com/ThexXTURBOXx/dex2jar after testing the `classes.dex` provided. Try testing using the latest release download on that branch.

**Comment by pxb1988** [comment]
the field `Landroid/support/design/widget/HeaderBehavior$a;->b:Landroid/view/View;` have a signature `TV` crashes the `SignatureReader` in asm

a workaround is already patched, 
https://github.com/pxb1988/dex2jar/commit/5e4c90f7150ffe16d98940448efd2bdb4a83245b
