### ISSUE TITLE
java.lang.RuntimeException: Method code too large!

### ISSUE THREAD

**Issue by p2kyc0ng** [pxb1988/dex2jar#467]
when i try to decomplie "AIDA 64" (version 1.78), there was an exception "java.lang.RuntimeException: Method code too large!" . u can download this app on google play or its website : https://www.aida64.com/news/aida64-android
There are 1 methods fail to translate.
2021-05-08 09:57:10 UTC
================= 0 ===================
Lcom/finalwire/aidaengine/DevModel;.getDevModel_Samsung()Ljava/lang/String;
java.lang.RuntimeException: Method code too large!
	at org.objectweb.asm.MethodWriter.getSize(MethodWriter.java:2036)
	at org.objectweb.asm.AsmBridge.sizeOfMethodWriter(AsmBridge.java:31)
	at com.googlecode.d2j.dex.ExDex2Asm.convertCode(ExDex2Asm.java:54)
	at com.googlecode.d2j.dex.Dex2jar$2.convertCode(Dex2jar.java:132)
	at com.googlecode.d2j.dex.Dex2Asm.convertMethod(Dex2Asm.java:575)
	at com.googlecode.d2j.dex.Dex2Asm.convertClass(Dex2Asm.java:434)
	at com.googlecode.d2j.dex.Dex2Asm.convertDex(Dex2Asm.java:450)
	at com.googlecode.d2j.dex.Dex2jar.doTranslate(Dex2jar.java:175)
	at com.googlecode.d2j.dex.Dex2jar.to(Dex2jar.java:275)
	at com.googlecode.dex2jar.tools.Dex2jarCmd.doCommandLine(Dex2jarCmd.java:112)
	at com.googlecode.dex2jar.tools.BaseCmd.doMain(BaseCmd.java:290)
	at com.googlecode.dex2jar.tools.Dex2jarCmd.main(Dex2jarCmd.java:33)

**Comment by p2kyc0ng** [comment]
![image](https://user-images.githubusercontent.com/48485920/117664684-a5eeb600-b1d4-11eb-81b0-bca2ee5ad10a.png)

i also find this FIXME in the code : FIXME handle 'java.lang.RuntimeException: Method code too large!'

**Comment by pxb1988** [comment]
please refer to https://github.com/pxb1988/dex2jar/pull/513, this should fix the `Method code too large!`

**Comment by p2kyc0ng** [comment]
copy, thx for reply
