### ISSUE TITLE
Decompiling error

### ISSUE THREAD

**Issue by manishpalarwal-786** [pxb1988/dex2jar#474]
dex2jar assets.dex -> .\assets-dex2jar.jar
Detail Error Information in File .\assets-error.zip
Please report this file to http://code.google.com/p/dex2jar/issues/entry if possible.
[assets-error.zip](https://github.com/pxb1988/dex2jar/files/6658360/assets-error.zip)

**Comment by manishpalarwal-786** [comment]
I have tried two times but always doing the same error

**Comment by pxb1988** [comment]
i have test the file in latest dex2jar, all class can translate to .class. but the asm complain on the generated .class file.

please notice the `8H` in the class name, which is not allow in class name.

````
Invalid type (must be a fully qualified class name in internal form): com/facebook/ads/redexgen/X/8H
java.lang.IllegalArgumentException: Invalid type (must be a fully qualified class name in internal form): com/facebook/ads/redexgen/X/8H
	at org.objectweb.asm.util.CheckMethodAdapter.checkInternalName(CheckMethodAdapter.java:1351)
	at org.objectweb.asm.util.CheckMethodAdapter.checkInternalName(CheckMethodAdapter.java:1318)
	at org.objectweb.asm.util.CheckMethodAdapter.visitTypeInsn(CheckMethodAdapter.java:665)
	at org.objectweb.asm.ClassReader.readCode(ClassReader.java:1444)
	at org.objectweb.asm.ClassReader.readMethod(ClassReader.java:1017)
	at org.objectweb.asm.ClassReader.accept(ClassReader.java:693)
	at org.objectweb.asm.ClassReader.accept(ClassReader.java:506)
	at com.googlecode.dex2jar.test.TestUtils.verify(TestUtils.java:244)
	at com.googlecode.dex2jar.test.TestUtils.verify(TestUtils.java:234)
	at com.googlecode.dex2jar.test.TestUtils.translateAndCheck(TestUtils.java:332)
````

at this time, we can't fix the issue, close it.
