### ISSUE TITLE
/res and AndroidManifest.xml not being properly decompiled. (An Issue that might be useful for the author)

### ISSUE THREAD

**Issue by Cloufish** [pxb1988/dex2jar#484]
`summary.txt`:
```
There are 49 methods fail to translate.
2021-07-30 07:03:35 UTC
version: [dex-reader-null, dex-reader-api-null, dex-ir-null, d2j-smali-null, d2j-base-cmd-null, dex-tools-null, dex-translator-null]
cmdline: [<CENSORED>/classes.dex, -o, <CENSORED>/classes.jar, -f]
env:
java.specification.version: 16
java.runtime.version: 16.0.1+9
java.class.path: /usr/local/bin/apkx-libs.jar
java.vm.vendor: Oracle Corporation
java.runtime.name: OpenJDK Runtime Environment
java.vendor.url: https://openjdk.java.net/
java.vm.name: OpenJDK 64-Bit Server VM
java.vm.specification.version: 16
java.vendor.url.bug: https://bugreport.java.com/bugreport/
java.io.tmpdir: /tmp
java.version: 16.0.1
java.specification.vendor: Oracle Corporation
java.vm.specification.name: Java Virtual Machine Specification
java.version.date: 2021-04-20
java.home: /usr/lib/jvm/java-16-openjdk
java.vm.compressedOopsMode: 32-bit
java.library.path: /usr/java/packages/lib:/usr/lib64:/lib64:/lib:/usr/lib
java.vm.info: mixed mode
java.vm.specification.vendor: Oracle Corporation
java.specification.name: Java Platform API Specification
java.vendor: N/A
java.vm.version: 16.0.1+9
java.class.version: 60.0
```
I got a bunch of other errors, contents of one of them:
```
Landroidx/recyclerview/widget/StaggeredGridLayoutManager$LazySpanLookup$FullSpanItem;.writeToParcel(Landroid/os/Parcel;I)V
java.lang.RuntimeException: can not merge I and Z
	at com.googlecode.dex2jar.ir.TypeClass.merge(TypeClass.java:100)
	at com.googlecode.dex2jar.ir.ts.TypeTransformer$TypeRef.updateTypeClass(TypeTransformer.java:174)
	at com.googlecode.dex2jar.ir.ts.TypeTransformer$TypeAnalyze.provideAs(TypeTransformer.java:780)
	at com.googlecode.dex2jar.ir.ts.TypeTransformer$TypeAnalyze.e1expr(TypeTransformer.java:496)
	at com.googlecode.dex2jar.ir.ts.TypeTransformer$TypeAnalyze.exExpr(TypeTransformer.java:713)
	at com.googlecode.dex2jar.ir.ts.TypeTransformer$TypeAnalyze.exExpr(TypeTransformer.java:703)
	at com.googlecode.dex2jar.ir.ts.TypeTransformer$TypeAnalyze.enexpr(TypeTransformer.java:698)
	at com.googlecode.dex2jar.ir.ts.TypeTransformer$TypeAnalyze.exExpr(TypeTransformer.java:719)
	at com.googlecode.dex2jar.ir.ts.TypeTransformer$TypeAnalyze.exExpr(TypeTransformer.java:703)
	at com.googlecode.dex2jar.ir.ts.TypeTransformer$TypeAnalyze.s1stmt(TypeTransformer.java:810)
	at com.googlecode.dex2jar.ir.ts.TypeTransformer$TypeAnalyze.sxStmt(TypeTransformer.java:840)
	at com.googlecode.dex2jar.ir.ts.TypeTransformer$TypeAnalyze.analyze(TypeTransformer.java:206)
	at com.googlecode.dex2jar.ir.ts.TypeTransformer.transform(TypeTransformer.java:44)
	at com.googlecode.d2j.dex.Dex2jar$2.optimize(Dex2jar.java:162)
	at com.googlecode.d2j.dex.Dex2Asm.convertCode(Dex2Asm.java:414)
	at com.googlecode.d2j.dex.ExDex2Asm.convertCode(ExDex2Asm.java:42)
	at com.googlecode.d2j.dex.Dex2jar$2.convertCode(Dex2jar.java:128)
	at com.googlecode.d2j.dex.Dex2Asm.convertMethod(Dex2Asm.java:509)
	at com.googlecode.d2j.dex.Dex2Asm.convertClass(Dex2Asm.java:406)
	at com.googlecode.d2j.dex.Dex2Asm.convertDex(Dex2Asm.java:422)
	at com.googlecode.d2j.dex.Dex2jar.doTranslate(Dex2jar.java:172)
	at com.googlecode.d2j.dex.Dex2jar.to(Dex2jar.java:272)
	at com.googlecode.dex2jar.tools.Dex2jarCmd.doCommandLine(Dex2jarCmd.java:108)
	at com.googlecode.dex2jar.tools.BaseCmd.doMain(BaseCmd.java:288)
	at com.googlecode.dex2jar.tools.Dex2jarCmd.main(Dex2jarCmd.java:32)


.method public writeToParcel(Landroid/os/Parcel;I)V
    .registers 4
    iget p2, p0, Landroidx/recyclerview/widget/StaggeredGridLayoutManager$LazySpanLookup$FullSpanItem;->mPosition:I
    invoke-virtual { p1, p2 }, Landroid/os/Parcel;->writeInt(I)V
    iget p2, p0, Landroidx/recyclerview/widget/StaggeredGridLayoutManager$LazySpanLookup$FullSpanItem;->mGapDir:I
    invoke-virtual { p1, p2 }, Landroid/os/Parcel;->writeInt(I)V
    iget-boolean p2, p0, Landroidx/recyclerview/widget/StaggeredGridLayoutManager$LazySpanLookup$FullSpanItem;->mHasUnwantedGapAfter:Z
    invoke-virtual { p1, p2 }, Landroid/os/Parcel;->writeInt(I)V
    iget-object p2, p0, Landroidx/recyclerview/widget/StaggeredGridLayoutManager$LazySpanLookup$FullSpanItem;->mGapPerSpan:[I
    if-eqz p2, :L0
    array-length v0, p2
    if-lez v0, :L0
    array-length p2, p2
    invoke-virtual { p1, p2 }, Landroid/os/Parcel;->writeInt(I)V
    iget-object p2, p0, Landroidx/recyclerview/widget/StaggeredGridLayoutManager$LazySpanLookup$FullSpanItem;->mGapPerSpan:[I
    invoke-virtual { p1, p2 }, Landroid/os/Parcel;->writeIntArray([I)V
    goto :L1
    :L0
    const/4 p2, 0
    invoke-virtual { p1, p2 }, Landroid/os/Parcel;->writeInt(I)V
    :L1
    return-void
.end method
```

**I don't understand, why all Java Classes still get decompiled. **, **What I want is a readable AndroidManifest.xml and /res folder to find strings found in R.java**

How to proceed from there? I'll try to find out but I would really appreciate hints :(

**Comment by ThexXTURBOXx** [comment]
This issue is most likely fixed on my branch: https://github.com/ThexXTURBOXx/dex2jar
