### ISSUE TITLE
d2j-jasmin2jar: "no viable alternative at input ..."

### ISSUE THREAD

**Issue by raulsiles** [pxb1988/dex2jar#5]
During the process of converting an APK file to a JAR file, the JAR file to Jasmin, when reverting back from Jasmin to a JAR file, using d2j-jasmin2jar v2.0, a "no viable alternative at input 'areturn'" error is generated. The same result is obtained with different APK files.

Input file: 
file.apk

Steps:
d2j-dex2jar -f -o file-dex2jar.jar file.apk 
d2j-jar2jasmin.sh -f -o file-dir file-dex2jar.jar 
d2j-jasmin2jar.sh -f -o file-edited.jar file-dir

Error:
$ d2j-jasmin2jar.sh -f -o color-edited.jar color-dir
assemble /sample/Color/color-dir -> color-edited.jar
/sample/Color/color-dir/android/support/v4/accessibilityservice/AccessibilityServiceInfoCompat$AccessibilityServiceInfoIcsImpl.j line 28:2 mismatched input ':' expecting '.end method'
/sample/Color/color-dir/android/support/v4/accessibilityservice/AccessibilityServiceInfoCompat.j line 92:4 mismatched character '"' expecting '''
/sample/Color/color-dir/android/support/v4/accessibilityservice/AccessibilityServiceInfoCompat.j line 93:0 no viable alternative at input 'areturn'
java.lang.NullPointerException
    at com.googlecode.d2j.jasmin.JasminParser.unEscape(JasminParser.java:356)
    at com.googlecode.d2j.jasmin.JasminParser.sField(JasminParser.java:5672)
    at com.googlecode.d2j.jasmin.JasminParser.sFile(JasminParser.java:1062)
    at com.googlecode.d2j.jasmin.JasminParser.parse(JasminParser.java:961)
    at com.googlecode.d2j.jasmin.Jasmin2JarCmd.assemble1(Jasmin2JarCmd.java:130)
    at com.googlecode.d2j.jasmin.Jasmin2JarCmd.access$0(Jasmin2JarCmd.java:121)
    at com.googlecode.d2j.jasmin.Jasmin2JarCmd$1.visitFile(Jasmin2JarCmd.java:114)
    at com.googlecode.d2j.jasmin.Jasmin2JarCmd$1.visitFile(Jasmin2JarCmd.java:1)
    at java.nio.file.Files.walkFileTree(Files.java:2670)
    at java.nio.file.Files.walkFileTree(Files.java:2742)
    at com.googlecode.d2j.jasmin.Jasmin2JarCmd.travelFileTree(Jasmin2JarCmd.java:110)
    at com.googlecode.d2j.jasmin.Jasmin2JarCmd.assemble0(Jasmin2JarCmd.java:99)
    at com.googlecode.d2j.jasmin.Jasmin2JarCmd.doCommandLine(Jasmin2JarCmd.java:92)
    at com.googlecode.dex2jar.tools.BaseCmd.doMain(BaseCmd.java:288)
    at com.googlecode.d2j.jasmin.Jasmin2JarCmd.main(Jasmin2JarCmd.java:56)

Sample file: color.apk
https://infotomb.com/so875.zip

Rename "so875.zip" to "color.apk".

**Comment by pxb1988** [comment]
the jasmin function is not fully tested, sorry for the inconvenient
