### ISSUE TITLE
d2j-dex2jar.bat ask for report this issue

### ISSUE THREAD

**Issue by RWareSteve** [pxb1988/dex2jar#500]
I launched

C:\Tools\dex2jar-2.0>d2j-dex2jar.bat -f base.apk

and got following output

dex2jar base.apk -> .\base-dex2jar.jar
Detail Error Information in File .\base-error.zip
Please report this file to http://code.google.com/p/dex2jar/issues/entry if possible.
java.util.IllegalFormatConversionException: d != java.lang.String
        at java.util.Formatter$FormatSpecifier.failConversion(Unknown Source)
        at java.util.Formatter$FormatSpecifier.printInteger(Unknown Source)
        at java.util.Formatter$FormatSpecifier.print(Unknown Source)
        at java.util.Formatter.format(Unknown Source)
        at java.util.Formatter.format(Unknown Source)
        at java.lang.String.format(Unknown Source)
        at com.googlecode.d2j.smali.BaksmaliDumpOut.s(BaksmaliDumpOut.java:62)
        at com.googlecode.d2j.smali.BaksmaliCodeDumper.visitFilledNewArrayStmt(BaksmaliCodeDumper.java:252)
        at com.googlecode.d2j.node.DexCodeNode$FilledNewArrayStmtNode.accept(DexCodeNode.java:300)
        at com.googlecode.d2j.node.DexCodeNode.accept(DexCodeNode.java:62)
        at com.googlecode.d2j.smali.BaksmaliDumper.baksmaliCode(BaksmaliDumper.java:517)
        at com.googlecode.d2j.smali.BaksmaliDumper.baksmaliMethod(BaksmaliDumper.java:445)
        at com.googlecode.d2j.smali.BaksmaliDumper.baksmaliMethod(BaksmaliDumper.java:403)
        at com.googlecode.dex2jar.tools.BaksmaliBaseDexExceptionHandler.dump(BaksmaliBaseDexExceptionHandler.java:132)
        at com.googlecode.dex2jar.tools.Dex2jarCmd.doCommandLine(Dex2jarCmd.java:117)
        at com.googlecode.dex2jar.tools.BaseCmd.doMain(BaseCmd.java:288)
        at com.googlecode.dex2jar.tools.Dex2jarCmd.main(Dex2jarCmd.java:32)

The input file: base.apk
                Is the Google Play application “Dexcom G6”
                Downloaded from FairPhone 3+ to local laptop by using Android Studio / File Explorer

[base-error.zip](https://github.com/pxb1988/dex2jar/files/7194410/base-error.zip)

**Comment by ThexXTURBOXx** [comment]
You need to launch `dex2jar` directly via `java -Xmx8G -jar dex2jar.jar [ARGUMENTS]`. The `-Xmx8G` gives Java 8 GB of RAM

**Comment by pxb1988** [comment]
the `java.util.IllegalFormatConversionException` is fixed in https://github.com/pxb1988/dex2jar/pull/217.

the m-3.txt is not fully dumped due to the `java.util.IllegalFormatConversionException`
the m-0,1,2.txt works, but fails on asm class check: `Invalid owner (must be a fully qualified class name in internal form): iz/࡫᫖`


https://github.com/pxb1988/dex2jar/releases/tag/v2.1 works on the app please have a try.

**Comment by RWareSteve** [comment]
great, it works! many thanks for this fix / hint.
