### ISSUE TITLE
d2j-dex2jar.sh fails with "java.lang.OutOfMemoryError: Java heap space" with 100GB of RAM and small file

### ISSUE THREAD

**Issue by reteps** [pxb1988/dex2jar#501]
I have been reverse-engineering an app and ran into a file that appears to completely break dex2jar. dex2jar successfully decompiles 5/6 other files, but this one appears to slowly climb in ram while making no progress. The file is <10Mb.

![image](https://user-images.githubusercontent.com/13869303/134097035-0d21dbc0-da7f-428d-a24d-25ef9643b2b7.png)

Here is a link to the file, [classes2.dex](https://drive.google.com/file/d/1VWL1KgLHADbcR223TdtzJwcRg32lP9hG/view?usp=sharing).

I am running the script `dex2jar.sh`, with the only modification being increasing the ram limit:

```
java -Xmx100G -classpath "${_classpath}" "com.googlecode.dex2jar.tools.Dex2jarCmd" "$@"
```

I then invoke it on the file like so:

```
$ /opt/dex2jar/tools-2.1/d2j-dex2jar.sh classes2.dex --force
```

**Comment by pxb1988** [comment]
the class `Lr4k;` caused the problem, i will check it out.

````
Java heap space
java.lang.OutOfMemoryError: Java heap space
	at java.base/java.util.LinkedList.linkLast(LinkedList.java:146)
	at java.base/java.util.LinkedList.add(LinkedList.java:342)
	at com.googlecode.d2j.converter.Dex2IRConverter.convert(Dex2IRConverter.java:136)
	at com.googlecode.d2j.dex.Dex2Asm.dex2ir(Dex2Asm.java:606)
	at com.googlecode.d2j.dex.Dex2Asm.convertCode(Dex2Asm.java:451)
	at com.googlecode.dex2jar.test.TestUtils$2.convertCode(TestUtils.java:301)
	at com.googlecode.d2j.dex.Dex2Asm.convertMethod(Dex2Asm.java:596)
	at com.googlecode.d2j.dex.Dex2Asm.convertClass(Dex2Asm.java:444)
	at com.googlecode.d2j.dex.Dex2Asm.convertClass(Dex2Asm.java:328)
	at com.googlecode.dex2jar.test.TestUtils.translateAndCheck(TestUtils.java:324)
	at com.googlecode.dex2jar.test.D2jTest$S$1$1.evaluate(D2jTest.java:82)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
	at com.googlecode.dex2jar.test.D2jTest$S$1.runChild(D2jTest.java:79)
	at com.googlecode.dex2jar.test.D2jTest$S$1.runChild(D2jTest.java:61)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
	at com.googlecode.dex2jar.test.D2jTest$S.runChild(D2jTest.java:115)
	at com.googlecode.dex2jar.test.D2jTest$S.runChild(D2jTest.java:45)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.runTestClass(JUnitTestClassExecutor.java:110)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.execute(JUnitTestClassExecutor.java:58)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.execute(JUnitTestClassExecutor.java:38)
	at org.gradle.api.internal.tasks.testing.junit.AbstractJUnitTestClassProcessor.processTestClass(AbstractJUnitTestClassProcessor.java:62)

````
