### ISSUE TITLE
AsmVerify - Issue  java.lang.IllegalArgumentException.

### ISSUE THREAD

**Issue by TamilanPeriyasamy** [pxb1988/dex2jar#52]
Any one Plz help me

java.lang.IllegalArgumentException: Landroid/support/a/g/f<TK;TV;>.android/support/a/g/h;: ';' expected at index 38
    at org.objectweb.asm.util.CheckMethodAdapter.checkChar(CheckMethodAdapter.java:1413)
    at org.objectweb.asm.util.CheckMethodAdapter.checkClassTypeSignature(CheckMethodAdapter.java:1295)
    at org.objectweb.asm.util.CheckMethodAdapter.checkFieldTypeSignature(CheckMethodAdapter.java:1260)
    at org.objectweb.asm.util.CheckMethodAdapter.checkFieldSignature(CheckMethodAdapter.java:1192)
    at org.objectweb.asm.util.CheckClassAdapter.visitField(CheckClassAdapter.java:450)
    at org.objectweb.asm.ClassReader.accept(ClassReader.java:669)
    at org.objectweb.asm.ClassReader.accept(ClassReader.java:426)
    at com.googlecode.dex2jar.tools.AsmVerify$1.handle(AsmVerify.java:126)
    at p.rn.util.FileWalker.walk(FileWalker.java:81)
    at com.googlecode.dex2jar.tools.AsmVerify.doCommandLine(AsmVerify.java:145)
    at com.googlecode.dex2jar.tools.BaseCmd.doMain(BaseCmd.java:169)
    at com.googlecode.dex2jar.tools.AsmVerify.main(AsmVerify.java:51)

**Comment by pxb1988** [comment]
seams there is a  invalid field signature on your class files, if it is generate by dex2jar, please attach it here

**Comment by TamilanPeriyasamy** [comment]
Okay thanks to U..
I attach with here given below..


Error values of signature
signature  is   Landroid/support/a/g/f<TK;TV;>.android/support/a/g/h;
Pos           is   38
c               is   ;


[com.facebook.shout.zip](https://github.com/pxb1988/dex2jar/files/97511/com.facebook.shout.zip)

**Comment by TamilanPeriyasamy** [comment]
Okay thanks to U..
I attach with here given below..


Error values of signature
signature  is   Landroid/support/a/g/f<TK;TV;>.android/support/a/g/h;
Pos           is   38
c               is   ;


[com.facebook.shout.zip](https://github.com/pxb1988/dex2jar/files/97511/com.facebook.shout.zip)

**Comment by TamilanPeriyasamy** [comment]
Hi friends plz help me ...........!
This high priority issue for me.....!

**Comment by pxb1988** [comment]
i have finally get the failing jar and find the original apk file from https://apkpure.com/shout-for-messenger/com.facebook.shout (sorry for my stupid internet connection)

in the apk there exists the following signiture, 

```
.field private d:Landroid/support/v7/internal/widget/s;
    .annotation system Ldalvik/annotation/Signature;
        value = {
            "Landroid/support/v7/internal/widget/p",
            "<TT;>.android/support/v7/internal/widget/s;"
        }
    .end annotation
.end field
```

dex2jar combine the two strings.  and result

```
.field private d Landroid/support/v7/internal/widget/s;
.signature "Landroid/support/v7/internal/widget/p<TT;>.android/support/v7/internal/widget/s;"
.end field
```

```
java.lang.IllegalArgumentException: Landroid/support/v7/internal/widget/p<TT;>.android/support/v7/internal/widget/s;: ';' expected at index 50
        at org.objectweb.asm.util.CheckClassAdapter.checkChar(CheckClassAdapter.java:992)
        at org.objectweb.asm.util.CheckClassAdapter.checkClassTypeSignature(CheckClassAdapter.java:865)
        at org.objectweb.asm.util.CheckClassAdapter.checkFieldTypeSignature(CheckClassAdapter.java:829)
        at org.objectweb.asm.util.CheckClassAdapter.checkFieldSignature(CheckClassAdapter.java:688)
        at org.objectweb.asm.util.CheckClassAdapter.visitField(CheckClassAdapter.java:480)
        at org.objectweb.asm.ClassReader.readField(ClassReader.java:768)
        at org.objectweb.asm.ClassReader.accept(ClassReader.java:689)
        at org.objectweb.asm.ClassReader.accept(ClassReader.java:506)
        at com.googlecode.dex2jar.tools.AsmVerify$1.visitFile(AsmVerify.java:136)
        at com.googlecode.dex2jar.tools.BaseCmd$1.visitFile(BaseCmd.java:56)
        at com.googlecode.dex2jar.tools.BaseCmd$1.visitFile(BaseCmd.java:53)
        at java.nio.file.FileTreeWalker.walk(FileTreeWalker.java:135)
        at java.nio.file.FileTreeWalker.walk(FileTreeWalker.java:199)
```

I am going to dig deeper, to figure out what happening.

**Comment by TamilanPeriyasamy** [comment]
I got solution for this issue.

I debugged given below...
// Not worked: 
.signature "Landroid/support/v7/internal/widget/p<TT;>.android/support/v7/internal/widget/s;"
// worked:
 .signature "Landroid/support/v7/internal/widget/p<TT;>.s;"

So..
.field private d Landroid/support/v7/internal/widget/s;
 .signature "Landroid/support/v7/internal/widget/p<TT;>.s;"
.end field
Correctly worked this one.(This is correct or not.)

**Comment by TamilanPeriyasamy** [comment]
Okay thanks....

**Comment by pxb1988** [comment]
tried with the following java code, it generate a field signature `Lres/Gh56Signature<TT;>.TestInner;`

``` java
public class Gh56Signature<T extends List> extends ArrayList {
    private class TestInner implements Runnable {
        @Override
        public void run() { }
    }

    TestInner testInner;

    public static void main(String... args) throws NoSuchFieldException {

        Field field = Gh56Signature.class.getDeclaredField("testInner");
        ParameterizedType t = (ParameterizedType) field.getGenericType();

        System.out.println("raw: " + t.getRawType());
        System.out.println("owner: " + t.getOwnerType());
        for (Type a : t.getActualTypeArguments()) {
            System.out.println("ta: " + a);
        }
    }
}
```

the default output is

```
raw: class res.Gh56Signature$TestInner
owner: res.Gh56Signature<T>
```

If the class `res/Gh56Signature$TestInner` is renamed to `res/Gh56Signature/TestInner` by Proguard will generate the bad signature `Lres/Gh56Signature<TT;>.res/Gh56Signature/TestInner;`

the code can neither run on Oracle JDK8

```
Exception in thread "main" java.lang.reflect.GenericSignatureFormatError
        at sun.reflect.generics.parser.SignatureParser.error(SignatureParser.java:126)
        at sun.reflect.generics.parser.SignatureParser.parseSimpleClassTypeSignature(SignatureParser.java:369)
        at sun.reflect.generics.parser.SignatureParser.parseClassTypeSignatureSuffix(SignatureParser.java:380)
        at sun.reflect.generics.parser.SignatureParser.parseClassTypeSignature(SignatureParser.java:314)
        at sun.reflect.generics.parser.SignatureParser.parseFieldTypeSignature(SignatureParser.java:291)
        at sun.reflect.generics.parser.SignatureParser.parseFieldTypeSignature(SignatureParser.java:285)
        at sun.reflect.generics.parser.SignatureParser.parseTypeSignature(SignatureParser.java:487)
        at sun.reflect.generics.parser.SignatureParser.parseTypeSig(SignatureParser.java:190)
        at sun.reflect.generics.repository.FieldRepository.parse(FieldRepository.java:52)
        at sun.reflect.generics.repository.FieldRepository.parse(FieldRepository.java:42)
        at sun.reflect.generics.repository.AbstractRepository.<init>(AbstractRepository.java:74)
        at sun.reflect.generics.repository.FieldRepository.<init>(FieldRepository.java:48)
        at sun.reflect.generics.repository.FieldRepository.make(FieldRepository.java:66)
        at java.lang.reflect.Field.getGenericInfo(Field.java:99)
        at java.lang.reflect.Field.getGenericType(Field.java:237)
        at res.Gh56Signature.main(Unknown Source)
```

nor run on Android 5.1.1 ART

```
java.lang.reflect.GenericSignatureFormatError
        at libcore.reflect.GenericSignatureParser.expect(GenericSignatureParser.java:473)
        at libcore.reflect.GenericSignatureParser.parseClassTypeSignature(GenericSignatureParser.java:332)
        at libcore.reflect.GenericSignatureParser.parseFieldTypeSignature(GenericSignatureParser.java:289)
        at libcore.reflect.GenericSignatureParser.parseForField(GenericSignatureParser.java:218)
        at java.lang.reflect.Field.getGenericType(Field.java:215)
        at res.Gh56Signature.main(Gh56Signature.java)
```

I have also tried to run the code without calling `Field.getGenericType()`, the code works fine.

here is my conclusion:
1. the format of field signature required a name after the '.' (DOT) not a internal class name
2. this case is caused by obfuscation
3. we can ignore error on `asm-verify`, since the code should works fine if the signature is not accessed. (a warning message should be ok for this case)
