### ISSUE TITLE
classes.dex to Jar Conversion Issue:         com.googlecode.dex2jar.DexException: while accept method:[La/a/a;.bc()Ljava/lang/String;]

### ISSUE THREAD

**Issue by TamilanPeriyasamy** [pxb1988/dex2jar#53]
Any one please help me....
     com.googlecode.dex2jar.DexException: while accept method:[La/a/a;.bc()Ljava/lang/String;]
        at com.googlecode.dex2jar.reader.DexFileReader.acceptMethod(DexFileReader.java:699)
        at com.googlecode.dex2jar.reader.DexFileReader.acceptClass(DexFileReader.java:446)
        at com.googlecode.dex2jar.reader.DexFileReader.accept(DexFileReader.java:328)
        at com.googlecode.dex2jar.v3.Dex2jar.doTranslate(Dex2jar.java:84)
        at com.googlecode.dex2jar.v3.Dex2jar.to(Dex2jar.java:239)
        at com.googlecode.dex2jar.v3.Dex2jar.to(Dex2jar.java:230)
        at com.googlecode.dex2jar.tools.Dex2jarCmd.doCommandLine(Dex2jarCmd.java:107)
        at com.googlecode.dex2jar.tools.BaseCmd.doMain(BaseCmd.java:168)
        at com.googlecode.dex2jar.tools.Dex2jarCmd.main(Dex2jarCmd.java:34)
      Caused by: com.googlecode.dex2jar.DexException: while accept code in method:[La/a/a;.bc()Ljava/lang/String;]
        at com.googlecode.dex2jar.reader.DexFileReader.acceptMethod(DexFileReader.java:689)
        ... 8 more
      Caused by: java.lang.IllegalArgumentException: Id out of bound
        at com.googlecode.dex2jar.reader.DexFileReader.getType(DexFileReader.java:561)
        at com.googlecode.dex2jar.reader.DexOpcodeAdapter.x2c(DexOpcodeAdapter.java:356)
        at com.googlecode.dex2jar.reader.DexCodeReader.acceptInsn(DexCodeReader.java:649)
        at com.googlecode.dex2jar.reader.DexCodeReader.accept(DexCodeReader.java:330)
        at com.googlecode.dex2jar.reader.DexFileReader.acceptMethod(DexFileReader.java:686)
        ... 8 more

**Comment by bensh** [comment]
I am also having the same issue from an apk build from AndroidStudio 3.1.2

dex2jar D:\apps\com.bensh.fridanumbergame.apk -> D:\output\com.bensh.fridanumbergame-dex2jar.jar

com.googlecode.dex2jar.DexException: while accept method:[Landroid/support/graphics/drawable/AnimatorInflaterCompat;.loadAnimator(Landroid/content/Context;I)Landroid/animation/Animator;]
	at com.googlecode.dex2jar.reader.DexFileReader.acceptMethod(DexFileReader.java:694)
	at com.googlecode.dex2jar.reader.DexFileReader.acceptClass(DexFileReader.java:436)
	at com.googlecode.dex2jar.reader.DexFileReader.accept(DexFileReader.java:323)
	at com.googlecode.dex2jar.v3.Dex2jar.doTranslate(Dex2jar.java:85)
	at com.googlecode.dex2jar.v3.Dex2jar.to(Dex2jar.java:261)
	at com.googlecode.dex2jar.v3.Dex2jar.to(Dex2jar.java:252)
	at com.googlecode.dex2jar.tools.Dex2jarCmd.doCommandLine(Dex2jarCmd.java:110)
	at com.googlecode.dex2jar.tools.BaseCmd.doMain(BaseCmd.java:288)
	at com.googlecode.dex2jar.tools.Dex2jarCmd.main(Dex2jarCmd.java:34)
Caused by: com.googlecode.dex2jar.DexException: while accept parameter annotation in method:[Landroid/support/graphics/drawable/AnimatorInflaterCompat;.loadAnimator(Landroid/content/Context;I)Landroid/animation/Animator;], parameter:[0]
	at com.googlecode.dex2jar.reader.DexFileReader.acceptMethod(DexFileReader.java:663)
	... 8 more
Caused by: java.lang.RuntimeException: EOF
	at com.googlecode.dex2jar.reader.io.ArrayDataIn.readUByte(ArrayDataIn.java:131)
	at com.googlecode.dex2jar.reader.DexAnnotationReader.accept(DexAnnotationReader.java:49)
	at com.googlecode.dex2jar.reader.DexFileReader.acceptMethod(DexFileReader.java:660)
	... 8 more

APK I'm trying this on is available at the link below.
https://ufile.io/kdoqv

**Comment by bensh** [comment]
Any movement on a fix for this?
