### ISSUE TITLE
dex2jar failed

### ISSUE THREAD

**Issue by huyuguang** [pxb1988/dex2jar#54]
dex2jar ./framework.dex -> ./framework-dex2jar.jar
Detail Error Information in File ./framework-error.zip
Please report this file to http://code.google.com/p/dex2jar/issues/entry if possible.

Following is the m-0.txt

Landroid/preference/MultiSelectListPreference$1;.onClick(Landroid/content/DialogInterface;IZ)V
java.lang.RuntimeException: can not merge I and Z
    at com.googlecode.dex2jar.ir.TypeClass.merge(TypeClass.java:100)
    at com.googlecode.dex2jar.ir.ts.TypeTransformer$TypeRef.updateTypeClass(TypeTransformer.java:174)
    at com.googlecode.dex2jar.ir.ts.TypeTransformer$TypeAnalyze.provideAs(TypeTransformer.java:780)
    at com.googlecode.dex2jar.ir.ts.TypeTransformer$TypeAnalyze.enexpr(TypeTransformer.java:659)
    at com.googlecode.dex2jar.ir.ts.TypeTransformer$TypeAnalyze.exExpr(TypeTransformer.java:719)
    at com.googlecode.dex2jar.ir.ts.TypeTransformer$TypeAnalyze.exExpr(TypeTransformer.java:703)
    at com.googlecode.dex2jar.ir.ts.TypeTransformer$TypeAnalyze.enexpr(TypeTransformer.java:698)
    at com.googlecode.dex2jar.ir.ts.TypeTransformer$TypeAnalyze.exExpr(TypeTransformer.java:719)
    at com.googlecode.dex2jar.ir.ts.TypeTransformer$TypeAnalyze.exExpr(TypeTransformer.java:703)
    at com.googlecode.dex2jar.ir.ts.TypeTransformer$TypeAnalyze.s1stmt(TypeTransformer.java:810)
    at com.googlecode.dex2jar.ir.ts.TypeTransformer$TypeAnalyze.sxStmt(TypeTransformer.java:840)
    at com.googlecode.dex2jar.ir.ts.TypeTransformer$TypeAnalyze.analyze(TypeTransformer.java:206)
    at com.googlecode.dex2jar.ir.ts.TypeTransformer.transform(TypeTransformer.java:44)
    at com.googlecode.d2j.dex.Dex2jar$2.optimize(Dex2jar.java:162)
    at com.googlecode.d2j.dex.Dex2Asm.convertCode(Dex2Asm.java:414)
    at com.googlecode.d2j.dex.ExDex2Asm.convertCode(ExDex2Asm.java:42)
    at com.googlecode.d2j.dex.Dex2jar$2.convertCode(Dex2jar.java:128)
    at com.googlecode.d2j.dex.Dex2Asm.convertMethod(Dex2Asm.java:509)
    at com.googlecode.d2j.dex.Dex2Asm.convertClass(Dex2Asm.java:406)
    at com.googlecode.d2j.dex.Dex2Asm.convertDex(Dex2Asm.java:422)
    at com.googlecode.d2j.dex.Dex2jar.doTranslate(Dex2jar.java:172)
    at com.googlecode.d2j.dex.Dex2jar.to(Dex2jar.java:272)
    at com.googlecode.dex2jar.tools.Dex2jarCmd.doCommandLine(Dex2jarCmd.java:108)
    at com.googlecode.dex2jar.tools.BaseCmd.doMain(BaseCmd.java:288)
    at com.googlecode.dex2jar.tools.Dex2jarCmd.main(Dex2jarCmd.java:32)

.method public onClick(Landroid/content/DialogInterface;IZ)V
    .registers 7
    if-eqz p3, :L1
    iget-object v0, p0, Landroid/preference/MultiSelectListPreference$1;->this$0:Landroid/preference/MultiSelectListPreference;
    iget-object v1, p0, Landroid/preference/MultiSelectListPreference$1;->this$0:Landroid/preference/MultiSelectListPreference;
    invoke-static { v1 }, Landroid/preference/MultiSelectListPreference;->access$200(Landroid/preference/MultiSelectListPreference;)Ljava/util/Set;
    move-result-object v1
    iget-object v2, p0, Landroid/preference/MultiSelectListPreference$1;->this$0:Landroid/preference/MultiSelectListPreference;
    invoke-static { v2 }, Landroid/preference/MultiSelectListPreference;->access$100(Landroid/preference/MultiSelectListPreference;)[Ljava/lang/CharSequence;
    move-result-object v2
    aget-object v2, v2, p2
    invoke-interface { v2 }, Ljava/lang/CharSequence;->toString()Ljava/lang/String;
    move-result-object v2
    invoke-interface { v1, v2 }, Ljava/util/Set;->add(Ljava/lang/Object;)Z
    move-result v1
    invoke-static { v0, v1 }, Landroid/preference/MultiSelectListPreference;->access$076(Landroid/preference/MultiSelectListPreference;I)Z
    :L0
    return-void
    :L1
    iget-object v0, p0, Landroid/preference/MultiSelectListPreference$1;->this$0:Landroid/preference/MultiSelectListPreference;
    iget-object v1, p0, Landroid/preference/MultiSelectListPreference$1;->this$0:Landroid/preference/MultiSelectListPreference;
    invoke-static { v1 }, Landroid/preference/MultiSelectListPreference;->access$200(Landroid/preference/MultiSelectListPreference;)Ljava/util/Set;
    move-result-object v1
    iget-object v2, p0, Landroid/preference/MultiSelectListPreference$1;->this$0:Landroid/preference/MultiSelectListPreference;
    invoke-static { v2 }, Landroid/preference/MultiSelectListPreference;->access$100(Landroid/preference/MultiSelectListPreference;)[Ljava/lang/CharSequence;
    move-result-object v2
    aget-object v2, v2, p2
    invoke-interface { v2 }, Ljava/lang/CharSequence;->toString()Ljava/lang/String;
    move-result-object v2
    invoke-interface { v1, v2 }, Ljava/util/Set;->remove(Ljava/lang/Object;)Z
    move-result v1
    invoke-static { v0, v1 }, Landroid/preference/MultiSelectListPreference;->access$076(Landroid/preference/MultiSelectListPreference;I)Z
    goto :L0
.end method

**Comment by pxb1988** [comment]
I have fixed the issue on https://github.com/pxb1988/dex2jar/commit/a21374153ac196c3d325a9f52b33731c0fc334fb, could you please try it with the last dex2jar.

here is a how to build dex2jar from source
https://github.com/pxb1988/dex2jar/wiki/BuildFromSource

#10 #11

**Comment by redjohn** [comment]
I just ran into this error and building from source worked for me

**Comment by pxb1988** [comment]
the dex works on latest release https://github.com/pxb1988/dex2jar/releases please have a try.
