### ISSUE TITLE
java.lang.StringIndexOutOfBoundsException: begin 1, end -1, length 2

### ISSUE THREAD

**Issue by lijian17** [pxb1988/dex2jar#565]
我在使用过程中遇到个错误，详情如下：
```
D:\apk\dex-tools-2.1>d2j-dex2jar.bat classes2.dex
dex2jar classes2.dex -> .\classes2-dex2jar.jar
java.lang.StringIndexOutOfBoundsException: begin 1, end -1, length 2
        at java.base/java.lang.String.checkBoundsBeginEnd(String.java:3319)
        at java.base/java.lang.String.substring(String.java:1874)
        at org.objectweb.asm.signature.SignatureReader.parseType(SignatureReader.java:169)
        at org.objectweb.asm.signature.SignatureReader.acceptType(SignatureReader.java:130)
        at org.objectweb.asm.commons.Remapper.mapSignature(Remapper.java:162)
        at org.objectweb.asm.commons.RemappingClassAdapter.visitField(RemappingClassAdapter.java:90)
        at org.objectweb.asm.ClassVisitor.visitField(ClassVisitor.java:272)
        at com.googlecode.d2j.dex.Dex2Asm.convertField(Dex2Asm.java:488)
        at com.googlecode.d2j.dex.Dex2Asm.convertClass(Dex2Asm.java:439)
        at com.googlecode.d2j.dex.Dex2Asm.convertClass(Dex2Asm.java:357)
        at com.googlecode.d2j.dex.Dex2Asm.convertDex(Dex2Asm.java:460)
        at com.googlecode.d2j.dex.Dex2jar.doTranslate(Dex2jar.java:175)
        at com.googlecode.d2j.dex.Dex2jar.to(Dex2jar.java:275)
        at com.googlecode.dex2jar.tools.Dex2jarCmd.doCommandLine(Dex2jarCmd.java:112)
        at com.googlecode.dex2jar.tools.BaseCmd.doMain(BaseCmd.java:290)
        at com.googlecode.dex2jar.tools.Dex2jarCmd.main(Dex2jarCmd.java:33)
```

[classes2.zip](https://github.com/pxb1988/dex2jar/files/10227120/classes2.zip)

**Comment by ThexXTURBOXx** [comment]
Please **close this issue** and follow the steps in #563

**Comment by lijian17** [comment]
1、非常感谢您百忙之中抽空给我解答疑问。
2、我按照您给的链接 #563 ，然后去到您个人的分支下载了执行包，执行反编译，竟然成功了，没有报一开始的那个错误了[java.lang.StringIndexOutOfBoundsException: begin 1, end -1, length 2]
3、最后我直接给出，解决我问题的页面吧[也就是您的个人分支页面][https://github.com/ThexXTURBOXx/dex2jar](https://github.com/ThexXTURBOXx/dex2jar)
