### ISSUE TITLE
d2j-smali.sh

### ISSUE THREAD

**Issue by KingCrimsonJY** [pxb1988/dex2jar#579]
java.lang.RuntimeException: not support
        at com.googlecode.d2j.dex.writer.ev.EncodedValue.wrap(EncodedValue.java:124)
        at com.googlecode.d2j.dex.writer.AnnotationWriter$EncodedArrayAnnWriter.visit(AnnotationWriter.java:106)
        at com.googlecode.d2j.smali.AntlrSmaliUtil.acceptAnnotation(AntlrSmaliUtil.java:740)
        at com.googlecode.d2j.smali.AntlrSmaliUtil.acceptAnnotation(AntlrSmaliUtil.java:731)
        at com.googlecode.d2j.smali.AntlrSmaliUtil.acceptAnnotations(AntlrSmaliUtil.java:697)
        at com.googlecode.d2j.smali.AntlrSmaliUtil.acceptFile(AntlrSmaliUtil.java:46)
        at com.googlecode.d2j.smali.Smali.smali0(Smali.java:78)
        at com.googlecode.d2j.smali.Smali.smaliFile(Smali.java:42)
        at com.googlecode.d2j.smali.Smali$1.visitFile(Smali.java:103)
        at com.googlecode.d2j.smali.Smali$1.visitFile(Smali.java:91)
        at java.base/java.nio.file.Files.walkFileTree(Files.java:2812)
        at java.base/java.nio.file.Files.walkFileTree(Files.java:2885)
        at com.googlecode.d2j.smali.Smali.smali(Smali.java:91)
        at com.googlecode.d2j.smali.SmaliCmd.doCommandLine(SmaliCmd.java:68)
        at com.googlecode.dex2jar.tools.BaseCmd.doMain(BaseCmd.java:290)
        at com.googlecode.d2j.smali.SmaliCmd.main(SmaliCmd.java:26)

**Comment by ThexXTURBOXx** [comment]
See https://github.com/pxb1988/dex2jar/issues/578

**Comment by headfirst123** [comment]
你的来信已收到，谢谢
