### ISSUE TITLE
GLITCH: 0003 LBuilder;.testDeadEndTry(I)I | not enough space for reading instruction

### ISSUE THREAD

**Issue by sendaoYan** [pxb1988/dex2jar#581]
![image](https://github.com/pxb1988/dex2jar/assets/24123821/5c9d7388-434c-451b-9608-d34fe6331145)

```log
dex2jar classes.dex -> test.jar
GLITCH: 0003 LBuilder;.testDeadEndTry(I)I | not enough space for reading instruction
Detail Error Information in File ./classes-error.zip
Please report this file to https://github.com/pxb1988/dex2jar/issues if possible.
Exception in thread "main" java.lang.NoClassDefFoundError: com/googlecode/d2j/smali/Smali
        at com.googlecode.dex2jar.tools.BaksmaliBaseDexExceptionHandler.getVersionString(BaksmaliBaseDexExceptionHandler.java:69)
        at com.googlecode.dex2jar.tools.BaksmaliBaseDexExceptionHandler.dumpSummary(BaksmaliBaseDexExceptionHandler.java:168)
        at com.googlecode.dex2jar.tools.BaksmaliBaseDexExceptionHandler.dumpTxt0(BaksmaliBaseDexExceptionHandler.java:114)
        at com.googlecode.dex2jar.tools.BaksmaliBaseDexExceptionHandler.dumpZip(BaksmaliBaseDexExceptionHandler.java:131)
        at com.googlecode.dex2jar.tools.BaksmaliBaseDexExceptionHandler.dump(BaksmaliBaseDexExceptionHandler.java:88)
        at com.googlecode.dex2jar.tools.Dex2jarCmd.doCommandLine(Dex2jarCmd.java:120)
        at com.googlecode.dex2jar.tools.BaseCmd.doMain(BaseCmd.java:290)
        at com.googlecode.dex2jar.tools.Dex2jarCmd.main(Dex2jarCmd.java:33)
Caused by: java.lang.ClassNotFoundException: com.googlecode.d2j.smali.Smali
        at java.net.URLClassLoader.findClass(URLClassLoader.java:387)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
        ... 8 more

```

[classes-error.zip](https://github.com/pxb1988/dex2jar/files/11744468/classes-error.zip)

[classes.dex.zip](https://github.com/pxb1988/dex2jar/files/11744503/classes.dex.zip)

**Comment by headfirst123** [comment]
你的来信已收到，谢谢

**Comment by ThexXTURBOXx** [comment]
See #582
