### ISSUE TITLE
IndexOutOfBoundsException had happened in using dex-tools-v2.4 tool to decode jar package

### ISSUE THREAD

**Issue by imGeorge** [pxb1988/dex2jar#608]
dex2jar classes.dex -> ./classes-dex2jar.jar
java.lang.IndexOutOfBoundsException
	at java.base/java.nio.Buffer.checkIndex(Buffer.java:749)
	at java.base/java.nio.HeapByteBuffer.getInt(HeapByteBuffer.java:439)
	at com.googlecode.d2j.reader.DexFileReader.getType(DexFileReader.java:981)
	at com.googlecode.d2j.reader.DexFileReader.accept(DexFileReader.java:654)
	at com.googlecode.d2j.reader.DexFileReader.accept(DexFileReader.java:625)
	at com.googlecode.d2j.dex.Dex2jar.doTranslate(Dex2jar.java:86)
	at com.googlecode.d2j.dex.Dex2jar.to(Dex2jar.java:285)
	at com.googlecode.dex2jar.tools.Dex2jarCmd.doCommandLine(Dex2jarCmd.java:112)
	at com.googlecode.dex2jar.tools.BaseCmd.doMain(BaseCmd.java:288)
	at com.googlecode.dex2jar.tools.Dex2jarCmd.main(Dex2jarCmd.java:33)

**Comment by ThexXTURBOXx** [comment]
Not enough information to resolve
