### ISSUE TITLE
java.lang.IllegalArgumentException: UTF8 string too large

### ISSUE THREAD

**Issue by wg2001wg** [pxb1988/dex2jar#614]
Lcom/vungle/ads/internal/omsdk/Res;-><clinit>()V
java.lang.IllegalArgumentException: UTF8 string too large
	at org.objectweb.asm.ByteVector.putUTF8(ByteVector.java:255)
	at org.objectweb.asm.SymbolTable.addConstantUtf8(SymbolTable.java:774)
	at org.objectweb.asm.SymbolTable.addConstantUtf8Reference(SymbolTable.java:1007)
	at org.objectweb.asm.SymbolTable.addConstantString(SymbolTable.java:604)
	at org.objectweb.asm.SymbolTable.addConstant(SymbolTable.java:474)
	at org.objectweb.asm.MethodWriter.visitLdcInsn(MethodWriter.java:1280)
	at org.objectweb.asm.MethodVisitor.visitLdcInsn(MethodVisitor.java:562)
	at org.objectweb.asm.commons.MethodRemapper.visitLdcInsn(MethodRemapper.java:196)
	at org.objectweb.asm.tree.LdcInsnNode.accept(LdcInsnNode.java:75)
	at org.objectweb.asm.tree.InsnList.accept(InsnList.java:144)
	at org.objectweb.asm.tree.MethodNode.accept(MethodNode.java:749)
	at com.googlecode.d2j.dex.ExDex2Asm.convertCode(ExDex2Asm.java:52)
	at com.googlecode.d2j.dex.Dex2jar$2.convertCode(Dex2jar.java:130)
	at com.googlecode.d2j.dex.Dex2Asm.convertMethod(Dex2Asm.java:774)
	at com.googlecode.d2j.dex.Dex2Asm.convertClass(Dex2Asm.java:532)
	at com.googlecode.d2j.dex.Dex2Asm.convertClass(Dex2Asm.java:435)
	at com.googlecode.d2j.dex.Dex2Asm.convertDex(Dex2Asm.java:597)
	at com.googlecode.d2j.dex.Dex2jar.doTranslate(Dex2jar.java:185)
	at com.googlecode.d2j.dex.Dex2jar.to(Dex2jar.java:285)
	at com.googlecode.dex2jar.tools.Dex2jarCmd.doCommandLine(Dex2jarCmd.java:112)
	at com.googlecode.dex2jar.tools.BaseCmd.doMain(BaseCmd.java:288)
	at com.googlecode.dex2jar.tools.Dex2jarCmd.main(Dex2jarCmd.java:33)

[merge-error.zip](https://github.com/pxb1988/dex2jar/files/14427607/merge-error.zip)

**Comment by ThexXTURBOXx** [comment]
Maybe #486 fixes this, please try that out

**Comment by ThexXTURBOXx** [comment]
Stale issue and not enough information to replicate
