### ISSUE TITLE
smali to dex failed

### ISSUE THREAD

**Issue by joshuachenn** [pxb1988/dex2jar#635]
I use ./d2j-baksmali somedex.dex to create smali files, then go to assemble these smali files to dex:

./d2j-smali.sh somedex-out 
smali somedex-out -> out.dex
java.lang.RuntimeException: not support
	at com.googlecode.d2j.dex.writer.ev.EncodedValue.wrap(EncodedValue.java:136)
	at com.googlecode.d2j.dex.writer.AnnotationWriter$EncodedArrayAnnWriter.visit(AnnotationWriter.java:106)
	at com.googlecode.d2j.smali.AntlrSmaliUtil.acceptAnnotation(AntlrSmaliUtil.java:860)
	at com.googlecode.d2j.smali.AntlrSmaliUtil.acceptAnnotation(AntlrSmaliUtil.java:851)
	at com.googlecode.d2j.smali.AntlrSmaliUtil.acceptAnnotations(AntlrSmaliUtil.java:817)
	at com.googlecode.d2j.smali.AntlrSmaliUtil.acceptFile(AntlrSmaliUtil.java:46)
	at com.googlecode.d2j.smali.Smali.smali0(Smali.java:79)
	at com.googlecode.d2j.smali.Smali.smaliFile(Smali.java:45)
	at com.googlecode.d2j.smali.Smali$1.visitFile(Smali.java:103)
	at com.googlecode.d2j.smali.Smali$1.visitFile(Smali.java:91)
	at java.nio.file.Files.walkFileTree(Files.java:2670)
	at java.nio.file.Files.walkFileTree(Files.java:2742)
	at com.googlecode.d2j.smali.Smali.smali(Smali.java:91)
	at com.googlecode.d2j.smali.SmaliCmd.doCommandLine(SmaliCmd.java:67)
	at com.googlecode.dex2jar.tools.BaseCmd.doMain(BaseCmd.java:288)
	at com.googlecode.d2j.smali.SmaliCmd.main(SmaliCmd.java:26)

**Comment by headfirst123** [comment]
你的来信已收到，谢谢

**Comment by ThexXTURBOXx** [comment]
Please provide more information - for example the input file
