### ISSUE TITLE
d2j-dex2jar.sh shows java.lang.NoSuchMethodError: org.objectweb.asm.MethodWriter.getSize()

### ISSUE THREAD

**Issue by chunkaihwang** [pxb1988/dex2jar#80]
dex2jar flyme.apk -> flyme_jar.jar
Exception in thread "main" java.lang.NoSuchMethodError: org.objectweb.asm.MethodWriter.getSize()I
    at org.objectweb.asm.AsmBridge.sizeOfMethodWriter(AsmBridge.java:28)
    at com.googlecode.d2j.dex.ExDex2Asm.convertCode(ExDex2Asm.java:55)
    at com.googlecode.d2j.dex.Dex2jar$2.convertCode(Dex2jar.java:129)
    at com.googlecode.d2j.dex.Dex2Asm.convertMethod(Dex2Asm.java:537)
    at com.googlecode.d2j.dex.Dex2Asm.convertClass(Dex2Asm.java:434)
    at com.googlecode.d2j.dex.Dex2Asm.convertDex(Dex2Asm.java:450)
    at com.googlecode.d2j.dex.Dex2jar.doTranslate(Dex2jar.java:123)
    at com.googlecode.d2j.dex.Dex2jar.to(Dex2jar.java:272)
    at com.googlecode.dex2jar.tools.Dex2jarCmd.doCommandLine(Dex2jarCmd.java:107)
    at com.googlecode.dex2jar.tools.BaseCmd.doMain(BaseCmd.java:290)
    at com.googlecode.dex2jar.tools.Dex2jarCmd.main(Dex2jarCmd.java:33)

[flyme.apk.zip](https://github.com/pxb1988/dex2jar/files/324828/flyme.apk.zip)

The apk is flyme.apk is attached or could be downloaded from
http://xcglobe.com/flyme/
[flyme.apk.zip](https://github.com/pxb1988/dex2jar/files/324830/flyme.apk.zip)

**Comment by stranded-xxx** [comment]
我也遇到这个问题，请问你解决了吗？

**Comment by headfirst123** [comment]
你的来信已收到，谢谢

**Comment by ThexXTURBOXx** [comment]
@stranded-xxx Please follow the steps in #590

**Comment by stranded-xxx** [comment]
@ThexXTURBOXx 你好，我没发现有*-.error.zip文件，之前确实存在输出*-.error.zip文件的报错，但是我更新dex2jar文件后就解决了，我需要解决的是如下截图
![image](https://github.com/user-attachments/assets/497f1566-a909-478c-b2dc-3de7e24c46dc)

**Comment by ThexXTURBOXx** [comment]
您能否尝试完全删除当前的 dex2jar 安装，然后重新下载并安装 dex2jar？我怀疑 `lib` 文件夹中仍有一些旧库，它们混淆了类加载器。

**Comment by stranded-xxx** [comment]
@ThexXTURBOXx 我的问题已解决，非常感谢！

**Comment by ThexXTURBOXx** [comment]
太好了，非常感谢你的反馈！:)
